export type OBDConnectionType = 'wifi' | 'bluetooth' | 'usb'
export type OBDConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'error'

export interface OBDParameter {
  pid: string
  name: string
  value: number | string | null
  unit: string
  group: 'engine' | 'fuel' | 'electric' | 'exhaust' | 'diag' | 'hybrid' | 'turbo'
  raw?: string
}

export interface OBDFaultCode {
  code: string
  description: string
  system: 'powertrain' | 'chassis' | 'body' | 'network'
  severity: 'low' | 'medium' | 'high'
  pending?: boolean
  module?: string
}

export interface ReadinessMonitor {
  name: string
  supported: boolean
  ready: boolean
}

export interface OBDScanResult {
  timestamp: string
  connectionType: OBDConnectionType
  deviceName?: string
  faultCodes: OBDFaultCode[]
  parameters: OBDParameter[]
  readiness?: ReadinessMonitor[]
  vin?: string
  milOn?: boolean
  dtcCount?: number
  protocolUsed?: string
}

export interface OBDScannerState {
  status: OBDConnectionStatus
  connectionType: OBDConnectionType | null
  deviceName: string | null
  error: string | null
  scanResult: OBDScanResult | null
  isScanning: boolean
  scanStep?: string
}

// PIDs Mode 01 — couverture complète SAE J1979 + extensions diesel/hybride/turbo
export const OBD_PIDS = {
  // ── Moteur ────────────────────────────────────────────────────────────────────
  RPM:               { pid: '010C', name: 'Régime moteur',                    unit: 'tr/min', group: 'engine' as const },
  SPEED:             { pid: '010D', name: 'Vitesse',                          unit: 'km/h',   group: 'engine' as const },
  ENGINE_LOAD:       { pid: '0104', name: 'Charge moteur',                    unit: '%',      group: 'engine' as const },
  ABS_LOAD:          { pid: '0143', name: 'Charge absolue moteur',            unit: '%',      group: 'engine' as const },
  COOLANT_TEMP:      { pid: '0105', name: 'Temp. liquide refroidissement',    unit: '°C',     group: 'engine' as const },
  OIL_TEMP:          { pid: '015C', name: 'Temp. huile moteur',               unit: '°C',     group: 'engine' as const },
  INTAKE_TEMP:       { pid: '010F', name: 'Temp. air admission',              unit: '°C',     group: 'engine' as const },
  AMBIENT_TEMP:      { pid: '0146', name: 'Temp. extérieure',                 unit: '°C',     group: 'engine' as const },
  TIMING:            { pid: '010E', name: 'Avance allumage',                  unit: '°',      group: 'engine' as const },
  MAP:               { pid: '010B', name: 'Pression admission (MAP)',         unit: 'kPa',    group: 'engine' as const },
  MAF:               { pid: '0110', name: 'Débit air massique (MAF)',         unit: 'g/s',    group: 'engine' as const },
  RUN_TIME:          { pid: '011F', name: 'Temps moteur actif',               unit: 's',      group: 'engine' as const },
  THROTTLE_REL:      { pid: '0145', name: 'Position papillon relative',       unit: '%',      group: 'engine' as const },
  THROTTLE_B:        { pid: '0147', name: 'Position papillon B',              unit: '%',      group: 'engine' as const },
  ACCEL_PEDAL_D:     { pid: '0149', name: 'Position pédale accélérateur D',   unit: '%',      group: 'engine' as const },
  ACCEL_PEDAL_E:     { pid: '014A', name: 'Position pédale accélérateur E',   unit: '%',      group: 'engine' as const },
  COMMANDED_THROTTLE:{ pid: '014C', name: 'Papillon commandé',                unit: '%',      group: 'engine' as const },
  TORQUE_DEMAND:     { pid: '0161', name: 'Couple moteur demandé',            unit: '%',      group: 'engine' as const },
  TORQUE_ACTUAL:     { pid: '0162', name: 'Couple moteur réel',               unit: '%',      group: 'engine' as const },
  TORQUE_REF:        { pid: '0163', name: 'Couple moteur référence',          unit: 'Nm',     group: 'engine' as const },
  ENGINE_TORQUE_PCT: { pid: '0164', name: 'Couple % données moteur',          unit: '%',      group: 'engine' as const },

  // ── Carburant ─────────────────────────────────────────────────────────────────
  STFT_B1:           { pid: '0106', name: 'Correction CT carburant Banc 1',   unit: '%',      group: 'fuel' as const },
  LTFT_B1:           { pid: '0107', name: 'Correction LT carburant Banc 1',   unit: '%',      group: 'fuel' as const },
  STFT_B2:           { pid: '0108', name: 'Correction CT carburant Banc 2',   unit: '%',      group: 'fuel' as const },
  LTFT_B2:           { pid: '0109', name: 'Correction LT carburant Banc 2',   unit: '%',      group: 'fuel' as const },
  FUEL_PRESSURE:     { pid: '010A', name: 'Pression carburant (rail)',        unit: 'kPa',    group: 'fuel' as const },
  FUEL_PRESSURE_ABS: { pid: '0123', name: 'Pression rail absolue (HP)',       unit: 'kPa',    group: 'fuel' as const },
  FUEL_LEVEL:        { pid: '012F', name: 'Niveau réservoir carburant',       unit: '%',      group: 'fuel' as const },
  FUEL_RATE:         { pid: '015E', name: 'Consommation instantanée',         unit: 'L/h',    group: 'fuel' as const },
  FUEL_TYPE:         { pid: '0151', name: 'Type carburant',                   unit: '',       group: 'fuel' as const },
  ETHANOL_PCT:       { pid: '0152', name: 'Pourcentage éthanol',              unit: '%',      group: 'fuel' as const },
  EQUIV_RATIO:       { pid: '0144', name: 'Ratio air/carburant commandé',     unit: 'λ',      group: 'fuel' as const },
  FUEL_SYSTEM_STATUS:{ pid: '0103', name: 'État système carburant',           unit: '',       group: 'fuel' as const },

  // ── Turbo / suralimentation ───────────────────────────────────────────────────
  BOOST_PRESSURE:    { pid: '0170', name: 'Pression de suralimentation',      unit: 'kPa',    group: 'turbo' as const },
  BOOST_COMMANDED:   { pid: '0172', name: 'Pression turbo commandée',         unit: 'kPa',    group: 'turbo' as const },
  TURBO_INLET_TEMP:  { pid: '0174', name: 'Temp. entrée turbo',               unit: '°C',     group: 'turbo' as const },
  TURBO_OUTLET_TEMP: { pid: '0175', name: 'Temp. sortie turbo',               unit: '°C',     group: 'turbo' as const },
  TURBO_RPM:         { pid: '0176', name: 'Régime turbo',                     unit: 'tr/min', group: 'turbo' as const },
  CHARGE_AIR_TEMP:   { pid: '0177', name: 'Temp. air après refroidisseur',    unit: '°C',     group: 'turbo' as const },

  // ── Électrique ────────────────────────────────────────────────────────────────
  THROTTLE:          { pid: '0111', name: 'Position papillon',                unit: '%',      group: 'electric' as const },
  BATTERY:           { pid: '0142', name: 'Tension batterie 12V',             unit: 'V',      group: 'electric' as const },
  BARO:              { pid: '0133', name: 'Pression atmosphérique',           unit: 'kPa',    group: 'electric' as const },
  CONTROL_MODULE_V:  { pid: '0142', name: 'Tension module contrôle',          unit: 'V',      group: 'electric' as const },

  // ── Échappement / Émissions ───────────────────────────────────────────────────
  O2_B1S1_VOLT:      { pid: '0114', name: 'Sonde O2 Banc1-Sonde1 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B1S2_VOLT:      { pid: '0115', name: 'Sonde O2 Banc1-Sonde2 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B2S1_VOLT:      { pid: '0118', name: 'Sonde O2 Banc2-Sonde1 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B2S2_VOLT:      { pid: '0119', name: 'Sonde O2 Banc2-Sonde2 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_WIDE_B1S1:      { pid: '0134', name: 'Lambda large bande B1S1',          unit: 'λ',      group: 'exhaust' as const },
  CATALYST_TEMP_B1S1:{ pid: '013C', name: 'Temp. catalyseur B1 Sonde1',       unit: '°C',     group: 'exhaust' as const },
  CATALYST_TEMP_B2S1:{ pid: '013D', name: 'Temp. catalyseur B2 Sonde1',       unit: '°C',     group: 'exhaust' as const },
  COMMANDED_EGR:     { pid: '012C', name: 'EGR commandé',                     unit: '%',      group: 'exhaust' as const },
  EGR_ERROR:         { pid: '012D', name: 'Erreur EGR',                       unit: '%',      group: 'exhaust' as const },
  COMMANDED_PURGE:   { pid: '012E', name: 'Purge canister commandée',         unit: '%',      group: 'exhaust' as const },
  EVAP_PRESSURE:     { pid: '0132', name: 'Pression vapeurs EVAP',            unit: 'Pa',     group: 'exhaust' as const },
  DPF_INLET_TEMP:    { pid: '017C', name: 'Temp. entrée FAP',                 unit: '°C',     group: 'exhaust' as const },
  DPF_DELTA_PRESS:   { pid: '017A', name: 'Pression différentielle FAP',      unit: 'kPa',    group: 'exhaust' as const },
  NOX_PRE_SCR:       { pid: '0183', name: 'NOx avant SCR',                    unit: 'ppm',    group: 'exhaust' as const },
  ADBLUE_LEVEL:      { pid: '019B', name: 'Niveau AdBlue',                    unit: '%',      group: 'exhaust' as const },

  // ── Hybride / EV ──────────────────────────────────────────────────────────────
  HYBRID_BATT_REM:   { pid: '015B', name: 'Batterie hybride restante',        unit: '%',      group: 'hybrid' as const },

  // ── Diagnostic ────────────────────────────────────────────────────────────────
  MIL_TIME:          { pid: '014D', name: 'Durée voyant MIL allumé',          unit: 'min',    group: 'diag' as const },
  DIST_MIL:          { pid: '0121', name: 'Distance avec MIL allumé',         unit: 'km',     group: 'diag' as const },
  DIST_CLEAR:        { pid: '0131', name: 'Distance depuis effacement',       unit: 'km',     group: 'diag' as const },
  WARMUPS_CLEAR:     { pid: '0130', name: 'Cycles chauffe depuis reset',      unit: '',       group: 'diag' as const },
  TIME_CLEAR:        { pid: '014E', name: 'Temps depuis reset codes',         unit: 'min',    group: 'diag' as const },
} as const

export const DTC_SYSTEM_MAP: Record<string, OBDFaultCode['system']> = {
  P: 'powertrain',
  C: 'chassis',
  B: 'body',
  U: 'network',
}

// Codes DTC les plus fréquents (~250 entrées) — descriptions en français
export const KNOWN_DTC: Record<string, string> = {
  // ── Moteur / Powertrain (P-codes) ─────────────────────────────────────────────
  P0010: 'Position arbre à cames "A" (banc 1) — Actionneur défaillant',
  P0011: 'Position arbre à cames "A" (banc 1) — Avance excessive',
  P0012: 'Position arbre à cames "A" (banc 1) — Retard excessif',
  P0014: 'Position arbre à cames "B" (banc 1) — Avance excessive',
  P0016: 'Corrélation vilebrequin/arbre à cames banc 1',
  P0017: 'Corrélation vilebrequin/arbre à cames banc 1 (capteur B)',
  P0030: 'Sonde O2 B1S1 — Circuit chauffage défaillant',
  P0036: 'Sonde O2 B1S2 — Circuit chauffage défaillant',
  P0050: 'Sonde O2 B2S1 — Circuit chauffage défaillant',
  P0100: 'Débitmètre d\'air (MAF) — Circuit défaillant',
  P0101: 'Débitmètre d\'air (MAF) — Plage/performance hors limites',
  P0102: 'Débitmètre d\'air (MAF) — Signal trop faible',
  P0103: 'Débitmètre d\'air (MAF) — Signal trop élevé',
  P0105: 'Capteur pression admission (MAP) — Circuit défaillant',
  P0106: 'Capteur MAP — Plage/performance',
  P0107: 'Capteur MAP — Signal trop faible',
  P0108: 'Capteur MAP — Signal trop élevé',
  P0110: 'Capteur température admission — Circuit défaillant',
  P0111: 'Capteur température admission — Plage/performance',
  P0112: 'Capteur température admission — Signal trop faible',
  P0113: 'Capteur température admission — Signal trop élevé',
  P0115: 'Capteur température liquide refroidissement — Circuit défaillant',
  P0116: 'Capteur température LDR — Plage/performance',
  P0117: 'Capteur température LDR — Signal trop faible',
  P0118: 'Capteur température LDR — Signal trop élevé',
  P0120: 'Capteur position papillon (TPS) — Circuit défaillant',
  P0121: 'Capteur TPS — Plage/performance',
  P0122: 'Capteur TPS — Signal trop faible',
  P0123: 'Capteur TPS — Signal trop élevé',
  P0128: 'Liquide refroidissement n\'atteint pas la temp. de régulation',
  P0130: 'Sonde lambda B1S1 — Circuit défaillant',
  P0131: 'Sonde lambda B1S1 — Tension trop faible',
  P0132: 'Sonde lambda B1S1 — Tension trop élevée',
  P0133: 'Sonde lambda B1S1 — Réponse lente',
  P0134: 'Sonde lambda B1S1 — Pas d\'activité détectée',
  P0135: 'Sonde lambda B1S1 — Chauffage défaillant',
  P0136: 'Sonde lambda B1S2 — Circuit défaillant',
  P0140: 'Sonde lambda B1S2 — Pas d\'activité détectée',
  P0141: 'Sonde lambda B1S2 — Chauffage défaillant',
  P0150: 'Sonde lambda B2S1 — Circuit défaillant',
  P0170: 'Système carburant — Réglage hors limites (Banc 1)',
  P0171: 'Système carburant — Mélange trop pauvre (Banc 1)',
  P0172: 'Système carburant — Mélange trop riche (Banc 1)',
  P0173: 'Système carburant — Réglage hors limites (Banc 2)',
  P0174: 'Système carburant — Mélange trop pauvre (Banc 2)',
  P0175: 'Système carburant — Mélange trop riche (Banc 2)',
  P0180: 'Capteur température carburant A — Défaut',
  P0190: 'Pression carburant rail — Circuit défaillant',
  P0191: 'Pression carburant rail — Plage/performance',
  P0192: 'Pression carburant rail — Trop faible',
  P0193: 'Pression carburant rail — Trop élevée',
  P0200: 'Circuit injecteur — Défaut général',
  P0201: 'Injecteur cylindre 1 — Circuit défaillant',
  P0202: 'Injecteur cylindre 2 — Circuit défaillant',
  P0203: 'Injecteur cylindre 3 — Circuit défaillant',
  P0204: 'Injecteur cylindre 4 — Circuit défaillant',
  P0205: 'Injecteur cylindre 5 — Circuit défaillant',
  P0206: 'Injecteur cylindre 6 — Circuit défaillant',
  P0217: 'Surchauffe moteur',
  P0219: 'Sur-régime moteur',
  P0220: 'Capteur position papillon B — Circuit défaillant',
  P0230: 'Pompe à carburant — Circuit défaillant',
  P0234: 'Suralimentation turbo trop élevée',
  P0235: 'Capteur pression suralimentation — Circuit défaillant',
  P0236: 'Capteur pression suralimentation — Plage/performance',
  P0237: 'Capteur pression suralimentation — Signal trop faible',
  P0238: 'Capteur pression suralimentation — Signal trop élevé',
  P0243: 'Wastegate turbo solenoïde A — Défaut',
  P0245: 'Wastegate turbo solenoïde A — Signal trop faible',
  P0299: 'Suralimentation turbo insuffisante (sous-pression)',
  P0300: 'Ratés d\'allumage aléatoires détectés (multi-cylindres)',
  P0301: 'Raté d\'allumage cylindre 1',
  P0302: 'Raté d\'allumage cylindre 2',
  P0303: 'Raté d\'allumage cylindre 3',
  P0304: 'Raté d\'allumage cylindre 4',
  P0305: 'Raté d\'allumage cylindre 5',
  P0306: 'Raté d\'allumage cylindre 6',
  P0307: 'Raté d\'allumage cylindre 7',
  P0308: 'Raté d\'allumage cylindre 8',
  P0315: 'Position vilebrequin — Variation non apprise',
  P0325: 'Capteur cliquetis (knock) banc 1 — Circuit défaillant',
  P0327: 'Capteur cliquetis banc 1 — Signal trop faible',
  P0335: 'Capteur position vilebrequin (CKP) — Circuit défaillant',
  P0336: 'Capteur position vilebrequin — Plage/performance',
  P0340: 'Capteur position arbre à cames (CMP) — Circuit défaillant',
  P0341: 'Capteur position arbre à cames — Plage/performance',
  P0351: 'Bobine d\'allumage A — Défaut primaire/secondaire',
  P0352: 'Bobine d\'allumage B — Défaut primaire/secondaire',
  P0353: 'Bobine d\'allumage C — Défaut primaire/secondaire',
  P0354: 'Bobine d\'allumage D — Défaut primaire/secondaire',
  P0380: 'Préchauffage diesel — Circuit défaillant',
  P0381: 'Préchauffage diesel — Voyant',
  P0400: 'EGR — Débit insuffisant',
  P0401: 'EGR — Débit insuffisant détecté',
  P0402: 'EGR — Débit excessif détecté',
  P0403: 'EGR — Circuit solénoïde défaillant',
  P0404: 'EGR — Plage/performance',
  P0405: 'Capteur position vanne EGR — Signal trop faible',
  P0406: 'Capteur position vanne EGR — Signal trop élevé',
  P0420: 'Catalyseur — Efficacité insuffisante (Banc 1)',
  P0421: 'Catalyseur de démarrage — Efficacité insuffisante (Banc 1)',
  P0430: 'Catalyseur — Efficacité insuffisante (Banc 2)',
  P0440: 'Système évaporation carburant — Défaut général',
  P0441: 'Système EVAP — Purge incorrecte',
  P0442: 'Système EVAP — Petite fuite détectée',
  P0443: 'Vanne purge canister — Circuit défaillant',
  P0446: 'Système EVAP — Vent control circuit',
  P0455: 'Système EVAP — Grosse fuite détectée',
  P0456: 'Système EVAP — Très petite fuite détectée',
  P0480: 'Ventilateur refroidissement 1 — Circuit défaillant',
  P0481: 'Ventilateur refroidissement 2 — Circuit défaillant',
  P0500: 'Capteur vitesse véhicule (VSS) — Défaut',
  P0501: 'Capteur vitesse véhicule — Plage/performance',
  P0505: 'Système ralenti (IAC) — Défaut',
  P0506: 'Régime ralenti trop bas',
  P0507: 'Régime ralenti trop élevé',
  P0560: 'Tension système — Défaut',
  P0562: 'Tension système — Trop faible',
  P0563: 'Tension système — Trop élevée',
  P0600: 'Bus communication série — Défaut interne',
  P0601: 'Module contrôle moteur (ECM) — Erreur mémoire interne',
  P0603: 'Module contrôle moteur — Mémoire KAM perdue',
  P0606: 'Module contrôle moteur — Défaut processeur',
  P0607: 'Module contrôle moteur — Performance',
  P0613: 'TCM — Défaut processeur',
  P0700: 'Système contrôle boîte de vitesses — Défaut général',
  P0715: 'Capteur vitesse entrée/turbine BV — Défaut',
  P0720: 'Capteur vitesse sortie BV — Défaut',
  P0721: 'Capteur vitesse sortie BV — Plage/performance',
  P0725: 'Capteur vitesse moteur — Entrée BV',
  P0730: 'Rapport incorrect détecté (BV)',
  P0731: 'Rapport 1 incorrect',
  P0732: 'Rapport 2 incorrect',
  P0733: 'Rapport 3 incorrect',
  P0734: 'Rapport 4 incorrect',
  P0740: 'Convertisseur de couple — Défaut verrouillage',
  P0741: 'Convertisseur de couple — Performance/coincé',
  P0750: 'Électrovanne BV A — Défaut',
  P0755: 'Électrovanne BV B — Défaut',
  P1000: 'Autodiagnostic en cours (readiness non complété)',
  P1004: 'Système VVT — Performance',
  P1101: 'MAF — Hors plage de fonctionnement',
  P1115: 'Capteur température LDR — Plage performance',
  P1128: 'Boucle fermée — Pas atteinte (banc 1)',
  P1131: 'Mélange trop pauvre banc 1 (apprentissage)',
  P1135: 'Sonde lambda B1S1 — Circuit chauffage',
  P1200: 'Circuit injecteur — Défaut',
  P1336: 'Apprentissage couple — Hors limites',
  P1351: 'Bobine d\'allumage — Tension primaire',
  P1400: 'EGR — Circuit solénoïde',
  P1421: 'Catalyseur AIR — Défaut',
  P1450: 'Pression vapeurs EVAP — Hors plage',
  P1500: 'VSS — Hors plage',
  P1610: 'Module immobiliseur — Défaut',
  P1700: 'TCM — Signal non valide',
  P2000: 'NOx — Catalyseur banc 1',
  P2002: 'Filtre à particules (FAP) — Efficacité hors plage banc 1',
  P2031: 'Capteur température FAP — Défaut',
  P2032: 'Capteur température FAP banc 1 sonde 2 — Signal faible',
  P2033: 'Capteur température FAP banc 1 sonde 2 — Signal élevé',
  P2080: 'Capteur température échappement banc 1 sonde 1 — Plage',
  P2096: 'Sonde post-cat banc 1 — Mélange trop pauvre',
  P2097: 'Sonde post-cat banc 1 — Mélange trop riche',
  P2122: 'Capteur pédale accélérateur D — Signal trop faible',
  P2138: 'Désaccord capteurs pédale D/E',
  P2187: 'Système carburant trop pauvre au ralenti banc 1',
  P2196: 'Sonde lambda B1S1 — Bloquée riche',
  P2197: 'Sonde lambda B1S1 — Bloquée pauvre',
  P2228: 'Capteur pression barométrique — Signal trop faible',
  P2237: 'Sonde lambda B1S1 — Circuit pompage défaut',
  P2261: 'Wastegate turbo — Mécanique bloquée',
  P2262: 'Wastegate turbo — Performance dégradée',
  P2270: 'Sonde lambda B1S2 — Bloquée pauvre',
  P2271: 'Sonde lambda B1S2 — Bloquée riche',
  P2279: 'Fuite d\'air admission',
  P2452: 'Capteur pression différentielle FAP — Circuit',
  P2453: 'Capteur pression différentielle FAP — Plage',
  P2454: 'Capteur pression différentielle FAP — Signal faible',
  P2455: 'Capteur pression différentielle FAP — Signal élevé',
  P2459: 'Régénération FAP — Fréquence excessive',
  P2463: 'FAP — Accumulation suie excessive',
  P244A: 'Pression différentielle FAP — Trop faible',
  P244B: 'Pression différentielle FAP — Trop élevée',
  P246C: 'FAP — Niveau saturation maximum',
  P2563: 'Capteur position turbo — Plage',
  P3000: 'Tension batterie hybride — Hors limites',

  // ── ABS / Châssis (C-codes) ───────────────────────────────────────────────────
  C0020: 'ABS — Défaut général système de freinage',
  C0031: 'Capteur vitesse roue AV gauche — Circuit ouvert',
  C0032: 'Capteur vitesse roue AV gauche — Court-circuit',
  C0033: 'Capteur vitesse roue AV gauche — Signal absent',
  C0034: 'Capteur vitesse roue AV droite — Défaut circuit',
  C0035: 'Capteur vitesse roue AV droite — Circuit ouvert',
  C0036: 'Capteur vitesse roue AV droite — Court-circuit',
  C0037: 'Capteur vitesse roue AV droite — Signal absent',
  C0040: 'Capteur vitesse roue AR droite — Défaut circuit',
  C0041: 'Capteur vitesse roue AR droite — Signal absent',
  C0042: 'Capteur vitesse roue AR droite — Court-circuit',
  C0045: 'Capteur vitesse roue AR gauche — Défaut circuit',
  C0046: 'Capteur vitesse roue AR gauche — Signal absent',
  C0047: 'Capteur vitesse roue AR gauche — Court-circuit',
  C0051: 'Capteur angle volant — Incohérence',
  C0060: 'Actionneur ABS — Défaut circuit',
  C0061: 'Actionneur ABS — Plage performance',
  C0065: 'Électrovanne ABS — Défaut',
  C0070: 'Moteur pompe ABS — Défaut circuit',
  C0071: 'Moteur pompe ABS — Sous-tension',
  C0110: 'Moteur pompe ABS — Défaillance',
  C0113: 'Capteur pression hydraulique — Défaut',
  C0121: 'Relais soupape ABS — Circuit défaillant',
  C0131: 'Capteur pression frein — Défaut',
  C0136: 'Capteur pression frein — Circuit défaillant',
  C0141: 'Solénoïde ABS gauche — Défaut circuit',
  C0148: 'Solénoïde ABS droit — Défaut circuit',
  C0161: 'Contacteur feux stop — Défaut circuit',
  C0162: 'Pédale de frein — Switch défaut',
  C0165: 'Capteur de lacet (ESP) — Défaut circuit',
  C0186: 'Capteur accélération latérale — Défaut',
  C0187: 'Capteur accélération latérale — Signal incohérent',
  C0196: 'Capteur taux de lacet / gyroscope (ESP) — Défaut',
  C0197: 'Capteur taux de lacet — Signal incohérent',
  C0200: 'Capteur accélération longitudinale — Défaut',
  C0210: 'Capteur vitesse transmission — Défaut circuit',
  C0221: 'Capteur vitesse AV droite — Circuit ouvert',
  C0245: 'Fréquence capteur vitesse roue — Erreur',
  C0265: 'Relais ABS — Défaut circuit',
  C0267: 'Moteur pompe ABS — Circuit ouvert / CC',
  C0269: 'Temps de décharge ABS excessif',
  C0281: 'Contacteur pédale de frein — Défaut circuit',
  C0284: 'Module ABS/ESP — Défaut interne',
  C0291: 'Perte communication avec BSI/BCM',
  C0292: 'Perte communication avec ECM',
  C0299: 'Perte communication ESP/VDC',
  C0561: 'ESP désactivé par utilisateur',
  C1000: 'Module ABS — Défaillance interne',
  C1010: 'Solénoïde ABS AV gauche',
  C1011: 'Solénoïde ABS AV droit',
  C1012: 'Solénoïde ABS AR gauche',
  C1013: 'Solénoïde ABS AR droit',
  C1094: 'Moteur pompe ABS — Tension hors limites',
  C1100: 'Moteur pompe ABS — Défaillance',
  C1121: 'Capteur vitesse roue AV gauche — Signal faible',
  C1122: 'Capteur vitesse roue AV droite — Signal faible',
  C1123: 'Capteur vitesse roue AR gauche — Signal faible',
  C1124: 'Capteur vitesse roue AR droite — Signal faible',
  C1145: 'Capteur d\'angle de volant — Défaut',
  C1155: 'Capteur vitesse roue AV gauche — Absence signal',
  C1156: 'Capteur vitesse roue AV droite — Absence signal',
  C1200: 'Capteur pression maître-cylindre — Défaut',
  C1210: 'Voyant ABS — Défaut',
  C1233: 'Capteur vitesse roue AV gauche — Signal absent',
  C1234: 'Capteur vitesse roue AV droite — Signal absent',
  C1235: 'Capteur vitesse roue AR droite — Signal absent',
  C1236: 'Capteur vitesse roue AR gauche — Signal absent',
  C1281: 'Direction assistée — Effort assistance défaut',

  // ── TPMS / Pression pneus (C-codes) ──────────────────────────────────────────
  C2200: 'TPMS — Module défaillant',
  C2202: 'TPMS — Voyant défaut',
  C2210: 'TPMS — Capteur AV gauche absent',
  C2211: 'TPMS — Capteur AV droit absent',
  C2212: 'TPMS — Capteur AR gauche absent',
  C2213: 'TPMS — Capteur AR droit absent',
  C2220: 'TPMS — Pression pneu trop basse',
  C2221: 'TPMS — Pression pneu trop élevée',

  // ── Direction assistée (C-codes) ─────────────────────────────────────────────
  C1500: 'EPS — Capteur couple défaillant',
  C1510: 'EPS — Moteur défaillant',
  C1511: 'EPS — Surchauffe moteur',
  C1520: 'EPS — Module défaillant',

  // ── Airbag / SRS (B-codes) ────────────────────────────────────────────────────
  B0001: 'Airbag conducteur — Circuit défaillant',
  B0002: 'Airbag passager — Circuit défaillant',
  B0010: 'Airbag rideau gauche — Défaut',
  B0011: 'Airbag rideau droit — Défaut',
  B0012: 'Airbag latéral gauche — Défaut',
  B0013: 'Airbag latéral droit — Défaut',
  B0020: 'Prétensionneur ceinture conducteur — Défaut',
  B0021: 'Prétensionneur ceinture passager — Défaut',
  B0028: 'Capteur impact côté gauche — Défaut',
  B0029: 'Capteur impact côté droit — Défaut',
  B0030: 'Capteur impact frontal — Défaut',
  B0051: 'Module airbag — Défaut interne',
  B0095: 'Désactivation airbag passager — Défaut',

  // ── Body / BCM / BSI (B-codes) ────────────────────────────────────────────────
  B1000: 'Module BSI/BCM — Défaut général',
  B1001: 'Module climatisation — Défaut',
  B1318: 'Tension batterie 12V — Trop faible (BSI)',
  B1320: 'Tension batterie 12V — Trop élevée (BSI)',
  B1500: 'Tableau de bord — Défaut interne',
  B1517: 'Combiné instrument — Défaut',
  B2000: 'Lève-vitres — Défaut moteur',
  B2100: 'Verrouillage centralisé — Défaut',
  B2200: 'Climatisation — Capteur évaporateur défaut',
  B2477: 'Compresseur clim — Embrayage défaut',
  B2600: 'Éclairage extérieur — Défaut',

  // ── Network / Réseau CAN (U-codes) ───────────────────────────────────────────
  U0001: 'Bus CAN haute vitesse — Défaut communication',
  U0002: 'Bus CAN haute vitesse — Perte communication',
  U0010: 'Bus CAN moyenne vitesse — Défaut communication',
  U0073: 'Bus CAN A — Off',
  U0100: 'Perte communication calculateur moteur (ECM/PCM)',
  U0101: 'Perte communication boîte de vitesses (TCM)',
  U0103: 'Perte communication module BV (GSM)',
  U0121: 'Perte communication module ABS/ESP',
  U0122: 'Perte communication module stabilité (VDC/ESP)',
  U0125: 'Perte communication module multi-axes',
  U0126: 'Perte communication capteur angle volant',
  U0140: 'Perte communication BSI/BCM',
  U0146: 'Perte communication module passerelle (gateway)',
  U0151: 'Perte communication module airbag',
  U0155: 'Perte communication tableau de bord (cluster)',
  U0164: 'Perte communication module climatisation',
  U0167: 'Perte communication module immobiliseur',
  U0184: 'Perte communication module radio',
  U0190: 'Perte communication module télématique',
  U0235: 'Perte communication régulateur de vitesse',
  U0301: 'Désaccord configuration ECM',
  U0401: 'Données invalides reçues du calculateur moteur',
  U0402: 'Données invalides reçues du TCM',
  U0415: 'Données invalides reçues du module ABS',
  U0418: 'Données invalides reçues du frein de stationnement',
  U0422: 'Données invalides reçues du BSI/BCM',
  U1000: 'Bus CAN classe 2 — Défaut',
  U1100: 'Perte communication moteur (Ford/Chrysler)',
  U1900: 'Bus CAN — Défaut communication général',

  // ── Moteur P-codes supplémentaires ────────────────────────────────────────────
  P0013: 'Position arbre à cames B (banc 1) — Actionneur',
  P0015: 'Position arbre à cames B (banc 1) — Retard excessif',
  P0018: 'Corrélation vilebrequin/arbre à cames banc 2',
  P0019: 'Corrélation vilebrequin/arbre à cames banc 2 (capteur B)',
  P0020: 'Position arbre à cames A (banc 2) — Actionneur',
  P0021: 'Position arbre à cames A (banc 2) — Avance excessive',
  P0022: 'Position arbre à cames A (banc 2) — Retard excessif',
  P0024: 'Position arbre à cames B (banc 2) — Avance excessive',
  P0031: 'Sonde O2 B1S1 — Chauffage tension trop faible',
  P0032: 'Sonde O2 B1S1 — Chauffage tension trop élevée',
  P0037: 'Sonde O2 B1S2 — Chauffage tension trop faible',
  P0038: 'Sonde O2 B1S2 — Chauffage tension trop élevée',
  P0040: 'Sondes O2 — Inversion B1S1/B2S1',
  P0051: 'Sonde O2 B2S1 — Chauffage tension trop faible',
  P0052: 'Sonde O2 B2S1 — Chauffage tension trop élevée',
  P0068: 'Désaccord MAP/MAF — Position papillon',
  P0070: 'Capteur température ambiante — Circuit',
  P0090: 'Régulateur pression carburant 1 — Circuit',
  P0091: 'Régulateur pression carburant 1 — Tension faible',
  P0092: 'Régulateur pression carburant 1 — Tension élevée',
  P0093: 'Système carburant — Fuite importante détectée',
  P0094: 'Système carburant — Petite fuite détectée',
  P0095: 'Capteur température air admission 2 — Circuit',
  P0097: 'Capteur température air admission 2 — Signal faible',
  P0098: 'Capteur température air admission 2 — Signal élevé',
  P0104: 'Débitmètre MAF — Signal intermittent',
  P0114: 'Capteur température admission — Signal intermittent',
  P0125: 'Temp insuffisante pour entrer en boucle fermée',
  P0126: 'Temp insuffisante pour fonctionnement stable',
  P0137: 'Sonde lambda B1S2 — Tension trop faible',
  P0138: 'Sonde lambda B1S2 — Tension trop élevée',
  P0139: 'Sonde lambda B1S2 — Réponse lente',
  P0151: 'Sonde lambda B2S1 — Tension trop faible',
  P0152: 'Sonde lambda B2S1 — Tension trop élevée',
  P0153: 'Sonde lambda B2S1 — Réponse lente',
  P0156: 'Sonde lambda B2S2 — Circuit défaillant',
  P0157: 'Sonde lambda B2S2 — Tension trop faible',
  P0158: 'Sonde lambda B2S2 — Tension trop élevée',
  P0181: 'Capteur température carburant — Plage/performance',
  P0182: 'Capteur température carburant — Tension faible',
  P0183: 'Capteur température carburant — Tension élevée',
  P0194: 'Pression carburant rail — Signal intermittent',
  P0201_PSA: 'Injecteur cyl. 1 — Circuit (PSA DF055)',
  P0207: 'Injecteur cylindre 7 — Circuit',
  P0208: 'Injecteur cylindre 8 — Circuit',
  P0221: 'Capteur papillon B — Plage/performance',
  P0222: 'Capteur papillon B — Signal faible',
  P0223: 'Capteur papillon B — Signal élevé',
  P0231: 'Pompe carburant — Circuit secondaire tension faible',
  P0232: 'Pompe carburant — Circuit secondaire tension élevée',
  P0240: 'Capteur turbo B — Plage/performance',
  P0246: 'Wastegate solénoïde A — Tension élevée',
  P0247: 'Wastegate solénoïde B — Circuit',
  P0260: 'Injecteur cylindre 1 — Mécanique défaillant',
  P0263: 'Cylindre 1 — Contribution/équilibre défaut',
  P0266: 'Cylindre 2 — Contribution/équilibre défaut',
  P0269: 'Cylindre 3 — Contribution/équilibre défaut',
  P0272: 'Cylindre 4 — Contribution/équilibre défaut',
  P0309: 'Raté d\'allumage cylindre 9',
  P0310: 'Raté d\'allumage cylindre 10',
  P0316: 'Ratés détectés au démarrage (premiers 1000 tours)',
  P0326: 'Capteur cliquetis banc 1 — Plage/performance',
  P0328: 'Capteur cliquetis banc 1 — Signal trop élevé',
  P0330: 'Capteur cliquetis banc 2 — Circuit',
  P0337: 'Capteur position vilebrequin — Signal faible',
  P0338: 'Capteur position vilebrequin — Signal élevé',
  P0342: 'Capteur position arbre à cames — Signal faible',
  P0343: 'Capteur position arbre à cames — Signal élevé',
  P0344: 'Capteur position arbre à cames — Signal intermittent',
  P0355: 'Bobine d\'allumage E — Défaut',
  P0356: 'Bobine d\'allumage F — Défaut',
  P0382: 'Préchauffage — Voyant défaut',
  P0383: 'Système préchauffage — Plage',
  P0407: 'Capteur position vanne EGR — Plage',
  P0408: 'Capteur position vanne EGR — Signal intermittent',
  P0409: 'Capteur EGR A — Circuit',
  P0410: 'Pompe air secondaire — Défaut',
  P0411: 'Pompe air secondaire — Débit incorrect',
  P0412: 'Solénoïde air secondaire — Circuit',
  P0418: 'Relais air secondaire A — Circuit',
  P0422: 'Catalyseur banc 1 — Efficacité au-dessous seuil',
  P0444: 'Vanne purge canister — Circuit ouvert',
  P0445: 'Vanne purge canister — Court-circuit',
  P0447: 'Vanne ventilation EVAP — Circuit ouvert',
  P0448: 'Vanne ventilation EVAP — Court-circuit',
  P0449: 'Vanne ventilation EVAP — Circuit',
  P0450: 'Capteur pression EVAP — Circuit',
  P0451: 'Capteur pression EVAP — Plage',
  P0452: 'Capteur pression EVAP — Signal faible',
  P0453: 'Capteur pression EVAP — Signal élevé',
  P0457: 'EVAP — Fuite bouchon de réservoir',
  P0461: 'Capteur niveau carburant — Plage',
  P0462: 'Capteur niveau carburant — Signal faible',
  P0463: 'Capteur niveau carburant — Signal élevé',
  P0464: 'Capteur niveau carburant — Intermittent',
  P0476: 'Vanne contre-pression échappement — Plage',
  P0478: 'Vanne contre-pression échappement — Signal élevé',
  P0490: 'Vanne EGR A — Circuit',
  P0491: 'Pompe air secondaire — Débit banc 1 insuffisant',
  P0498: 'Vanne ventilation EVAP — Tension faible',
  P0499: 'Vanne ventilation EVAP — Tension élevée',
  P0502: 'Capteur vitesse véhicule — Signal faible',
  P0503: 'Capteur vitesse véhicule — Signal intermittent/erratique',
  P0504: 'Désaccord capteurs frein A/B',
  P0508: 'Solénoïde régulation ralenti — Signal faible',
  P0509: 'Solénoïde régulation ralenti — Signal élevé',
  P0510: 'Contact papillon fermé — Défaut',
  P0520: 'Capteur pression huile — Circuit',
  P0521: 'Capteur pression huile — Plage',
  P0522: 'Capteur pression huile — Tension faible',
  P0523: 'Capteur pression huile — Tension élevée',
  P0524: 'Pression huile moteur — Trop basse',
  P0530: 'Capteur pression réfrigérant A/C — Circuit',
  P0532: 'Capteur pression réfrigérant A/C — Signal faible',
  P0533: 'Capteur pression réfrigérant A/C — Signal élevé',
  P0571: 'Contacteur pédale frein A — Circuit',
  P0572: 'Contacteur pédale frein A — Signal faible',
  P0602: 'ECM — Programmation invalide',
  P0604: 'ECM — Erreur RAM',
  P0605: 'ECM — Erreur ROM',
  P0608: 'ECM — Sortie référence A',
  P0617: 'Relais démarreur — Circuit élevé',
  P0620: 'Régulation alternateur — Défaut circuit',
  P0622: 'Champ alternateur F — Circuit',
  P0628: 'Pompe carburant A — Tension faible',
  P0629: 'Pompe carburant A — Tension élevée',
  P0650: 'Voyant MIL — Défaut circuit',
  P0651: 'Sortie référence B ECM — Circuit',
  P0660: 'Vanne admission variable banc 1 — Circuit',
  P0670: 'Module bougies préchauffage — Circuit',
  P0671: 'Bougie préchauffage cyl. 1 — Circuit',
  P0672: 'Bougie préchauffage cyl. 2 — Circuit',
  P0673: 'Bougie préchauffage cyl. 3 — Circuit',
  P0674: 'Bougie préchauffage cyl. 4 — Circuit',
  P0683: 'Bougies préchauffage — Communication ECM',
  P0685: 'Relais alimentation ECM — Circuit',
  P0686: 'Relais alimentation ECM — Signal faible',
  P0687: 'Relais alimentation ECM — Signal élevé',
  P0688: 'Relais alimentation ECM — Sens contrôle',
  P0691: 'Ventilateur 1 — Tension faible',
  P0692: 'Ventilateur 1 — Tension élevée',
  P0693: 'Ventilateur 2 — Tension faible',
  P0694: 'Ventilateur 2 — Tension élevée',
  P0701: 'BV — Plage performance',
  P0702: 'BV — Circuit électrique',
  P0703: 'Contacteur frein TCM — Circuit',
  P0705: 'TCM — Circuit position rapport (PRNDL)',
  P0706: 'TCM — Plage capteur position rapport',
  P0707: 'TCM — Signal faible capteur position',
  P0710: 'Capteur température BV — Circuit',
  P0711: 'Capteur température BV — Plage',
  P0712: 'Capteur température BV — Signal faible',
  P0713: 'Capteur température BV — Signal élevé',
  P0717: 'Capteur vitesse turbine — Signal absent',
  P0722: 'Capteur vitesse sortie BV — Signal absent',
  P0735: 'Rapport 5 — Incorrect',
  P0736: 'Marche arrière — Rapport incorrect',
  P0742: 'Convertisseur couple — Bloqué ON',
  P0751: 'Électrovanne BV A — Performance/bloqué OFF',
  P0752: 'Électrovanne BV A — Bloqué ON',
  P0753: 'Électrovanne BV A — Circuit électrique',
  P0756: 'Électrovanne BV B — Performance/bloqué OFF',
  P0757: 'Électrovanne BV B — Bloqué ON',
  P0760: 'Électrovanne BV C — Performance/bloqué OFF',
  P0761: 'Électrovanne BV C — Bloqué ON',
  P0765: 'Électrovanne BV D — Circuit',
  P0770: 'Électrovanne BV E — Circuit',
  P0775: 'Électrovanne BV F — Circuit',
  P0795: 'Électrovanne BV C — Circuit',
  P0796: 'Électrovanne BV C — Performance',
  P0810: 'Pédale embrayage — Position défaut',
  P0830: 'Contacteur pédale embrayage A — Circuit',
  P0850: 'Position pédale embrayage — Circuit',

  // ── Diesel / FAP / SCR / AdBlue (P2xxx) ──────────────────────────────────────
  P2014: 'IMRC — Capteur position banc 1 — Circuit',
  P2015: 'IMRC — Plage/performance banc 1',
  P2016: 'IMRC — Signal faible banc 1',
  P2017: 'IMRC — Signal élevé banc 1',
  P2046: 'Doseur AdBlue — Performance',
  P2047: 'Doseur AdBlue — Circuit faible',
  P2048: 'Doseur AdBlue — Circuit élevé',
  P2050: 'Doseur AdBlue — Performance',
  P2101: 'Position papillon moteur — Plage',
  P2102: 'Moteur papillon — Tension faible',
  P2103: 'Moteur papillon — Tension élevée',
  P2106: 'Système puissance moteur — Limite',
  P2110: 'Position papillon — Mode dégradé puissance',
  P2111: 'Système papillon — Bloqué ouvert',
  P2112: 'Système papillon — Bloqué fermé',
  P2115: 'Position pédale accélérateur D — Min stop',
  P2116: 'Position pédale accélérateur D — Max stop',
  P2120: 'Capteur pédale accélérateur D — Circuit',
  P2121: 'Capteur pédale accélérateur D — Plage',
  P2123: 'Capteur pédale accélérateur D — Signal élevé',
  P2125: 'Capteur pédale accélérateur E — Circuit',
  P2127: 'Capteur pédale accélérateur E — Signal faible',
  P2128: 'Capteur pédale accélérateur E — Signal élevé',
  P2135: 'Désaccord capteurs papillon A/B',
  P2178: 'Système carburant — Trop riche au ralenti (B1)',
  P2179: 'Système carburant — Trop pauvre à charge partielle (B1)',
  P2188: 'Système carburant — Trop riche au ralenti (B2)',
  P2189: 'Système carburant — Trop pauvre au ralenti (B2)',
  P2191: 'Système carburant — Trop pauvre à pleine charge (B1)',
  P2192: 'Système carburant — Trop riche à pleine charge (B1)',
  P2193: 'Système carburant — Trop pauvre à pleine charge (B2)',
  P2200: 'Capteur NOx 1 banc 1 — Circuit',
  P2201: 'Capteur NOx 1 banc 1 — Plage',
  P2202: 'Capteur NOx 1 banc 1 — Signal faible',
  P2229: 'Capteur baromètre — Signal élevé',
  P2231: 'Sonde lambda B1S1 — Tension entre signal et chauffage',
  P2238: 'Sonde lambda B1S1 — Circuit pompage signal faible',
  P2240: 'Sonde lambda B2S1 — Circuit pompage défaut',
  P2243: 'Sonde lambda B1S1 — Circuit référence',
  P2247: 'Sonde lambda B2S1 — Circuit référence',
  P2251: 'Sonde lambda B1S1 — Circuit retour faible',
  P2257: 'Pompe air secondaire — Circuit contrôle faible',
  P2258: 'Pompe air secondaire — Circuit contrôle élevé',
  P2263: 'Système turbocompresseur — Performance',
  P2299: 'Position pédale frein — Incohérence avec accélérateur',
  P2300: 'Bobine allumage A — Circuit primaire faible',
  P2301: 'Bobine allumage A — Circuit primaire élevé',
  P2303: 'Bobine allumage B — Circuit primaire faible',
  P2402: 'Pompe détection fuite EVAP — Circuit faible',
  P2415: 'Pompe détection fuite EVAP — Bloqué',
  P2425: 'EGR refroidi — Vanne by-pass circuit',
  P2428: 'Capteur température échappement banc 1 — Plage',
  P2431: 'Pompe air secondaire — Plage banc 1',
  P2432: 'Pompe air secondaire — Circuit signal faible',
  P2440: 'Vanne arrêt air secondaire B1 — Bloquée',
  P2458: 'Régénération FAP — Durée',
  P2461: 'FAP — Performance régénération',
  P2462: 'FAP — Niveau accumulation suies trop élevé',
  P2470: 'Sonde température échappement B1 — Plage',

  // ── Hybride / EV (P0Axx, P1Axx, P3xxx) ───────────────────────────────────────
  P0A00: 'Système haute tension — Défaut général',
  P0A09: 'Convertisseur DC-DC — Performance',
  P0A0D: 'Verrouillage haute tension — Défaut interne',
  P0A1F: 'Module batterie traction — Tension dégradée',
  P0A2A: 'Refroidissement batterie traction — Performance',
  P0A2B: 'Surchauffe batterie traction',
  P0A3C: 'Refroidissement onduleur — Performance',
  P0A3D: 'Surchauffe onduleur',
  P0A7F: 'Batterie hybride — Détérioration',
  P0A80: 'Remplacer pack batterie hybride',
  P0A81: 'Refroidisseur batterie traction — Bloqué',
  P0A82: 'Refroidisseur batterie traction — Circuit',
  P0AA6: 'Isolation haute tension — Défaut',
  P0AC2: 'Onduleur — Performance puissance moteur 1',
  P0B41: 'Module batterie 1 — Tension faible',

  // ── Codes constructeurs P1xxx — Renault/Peugeot/Citroën ──────────────────────
  P1100: 'MAF — Circuit intermittent',
  P1110: 'Géométrie variable turbo — Sous-actionneur',
  P1129: 'Système air admission — Fonctionnement',
  P1132: 'Mélange trop riche B1 (apprentissage saturé)',
  P1140: 'Capteur charge moteur — Plage',
  P1150: 'Sonde lambda B2S1 — Apprentissage saturé',
  P1170: 'Apprentissage mélange — Hors limites',
  P1188: 'Régulation richesse B1 — Hors limites',
  P1235: 'Pompe carburant — Activation incorrecte',
  P1352: 'Préchauffage — Voyant tension élevée',
  P1380: 'Système anti-ratés — Allumage défaut',
  P1383: 'Bobine allumage — Circuit primaire défaillant',
  P1402: 'Vanne EGR — Position circuit (PSA)',
  P1404: 'Vanne EGR — Position fermée incorrecte (Renault)',
  P1407: 'Capteur position EGR — Performance',
  P1410: 'Vanne EGR — Position ouverte (Renault)',
  P1438: 'Capteur position vanne EGR — Circuit',
  P1443: 'Vanne purge canister — Performance (Renault)',
  P1471: 'Système ventilation EVAP — Pression hors limites',
  P1480: 'Pompe air sec — Tension faible (Renault)',
  P1481: 'Pompe air sec — Tension élevée (Renault)',
  P1490: 'Pompe air sec — Pression non détectée',
  P1518: 'Position papillon — Bloquée ouverte',
  P1519: 'Position papillon — Bloquée fermée',
  P1525: 'Compresseur clim — Demande embrayage circuit',
  P1531: 'Régulateur de vitesse — Bouton circuit (PSA)',
  P1540: 'Régulateur de vitesse — Désactivé par défaut',
  P1571: 'Frein — Demande désactivation régulateur',
  P1599: 'Limite couple moteur — Demande BV (Renault)',
  P1600: 'PCM/TCM — Communication erratique',
  P1602: 'Module immobiliseur — Communication ECM',
  P1606: 'Carte ECM — Code accès incorrect',
  P1608: 'Module immobiliseur — Pas de réponse',
  P1611: 'Carte clé — Code transpondeur incorrect',
  P1616: 'Module immobiliseur — Communication',
  P1620: 'Module immobiliseur — Pas autorisation moteur',
  P1626: 'Module immobiliseur — Erreur mémoire',
  P1633: 'Module immobiliseur — Pile défaillante',
  P1640: 'Auto-diagnostic ECM — Mémoire EEPROM',
  P1652: 'Capteur vitesse roue — Référence (PSA)',
  P1670: 'Tension batterie 12V — Trop basse',
  P1671: 'Tension batterie 12V — Trop haute',
  P1689: 'Embrayage convertisseur — Performance',
  P1738: 'BV — Capteur vitesse turbine plage',
  P1745: 'BV — Pression hydraulique défaut',
  P1747: 'BV — Solénoïde régulation pression',
  P1760: 'BV — Pression ligne demande',
  P1762: 'BV — Solénoïde 2-3 défaut',

  // ── Codes constructeurs P1xxx — VAG (VW/Audi/Skoda/Seat) ─────────────────────
  P1102: 'Sonde lambda B1S1 — Chauffage résistance trop faible',
  P1105: 'Sonde lambda B1S2 — Chauffage résistance trop faible',
  P1116: 'Sonde lambda — Tension chauffage faible',
  P1117: 'Sonde lambda — Tension chauffage élevée',
  P1126: 'Pression carburant — Plage hors limites (VAG)',
  P1127: 'Pression carburant — Trop élevée (VAG)',
  P1136: 'Boucle fermée — Banc 1 mélange trop pauvre',
  P1137: 'Boucle fermée — Banc 1 mélange trop riche',
  P1141: 'Capteur charge MAF — Plage VAG',
  P1162: 'Capteur température carburant — Court-circuit masse',
  P1176: 'Régulation richesse — Banc 1 hors limites',
  P1192: 'Capteur volant moteur — Performance',
  P1213: 'Injecteur cylindre 1 — Court-circuit B+',
  P1214: 'Injecteur cylindre 2 — Court-circuit B+',
  P1215: 'Injecteur cylindre 3 — Court-circuit B+',
  P1216: 'Injecteur cylindre 4 — Court-circuit B+',
  P1247: 'Pompe carburant — Tension régulation',
  P1296: 'Système refroidissement — Défaut',
  P1306: 'Régulateur couple — Plage',
  P1325: 'Capteur cliquetis cylindre 1 — Régulation limite',
  P1340: 'Capteur PMH/vilebrequin — Pas signal',
  P1393: 'Bobine d\'allumage cyl. 1 — Sortie primaire',
  P1430: 'EVAP — Capteur fuite circuit',
  P1455: 'Ventilation moteur — Diagnostic capteur fuite',
  P1475: 'Vanne purge EVAP — Tension élevée VAG',
  P1545: 'Vanne EGR — Tension circuit VAG',
  P1546: 'Vanne EGR — Tension faible VAG',
  P1565: 'Régulateur de vitesse — Tension minimum',
  P1603: 'ECM — Performance interne',
  P1612: 'Module ECM — Codage défaut',
  P1613: 'Voyant MIL — Court-circuit masse',
  P1681: 'Limite couple moteur — Surchauffe',
  P1693: 'Capteur position embrayage — Circuit',
  P1733: 'Convertisseur couple — Verrouillage activation',

  // ── Codes Ford (P14xx) ───────────────────────────────────────────────────────
  P1401: 'Capteur pression EGR DPFE — Tension élevée',
  P1405: 'Capteur pression EGR DPFE — Capteur amont défaut',
  P1406: 'Capteur pression EGR DPFE — Capteur aval défaut',
  P1408: 'Capteur EGR — Hors plage',
  P1409: 'Régulateur EVR EGR — Circuit',
  P1411: 'Pompe air secondaire — Plage AM2',
  P1414: 'Pompe air sec — Pas de débit aval',
  P1505: 'Régulateur ralenti — Plage Ford',
  P1714: 'Solénoïde SS1 BV — Performance',

  // ── Codes BMW (P1xxx) ────────────────────────────────────────────────────────
  P1083: 'Sonde lambda 1 banc 1 — Régulation pauvre BMW',
  P1084: 'Sonde lambda 1 banc 1 — Régulation riche BMW',
  P1187: 'Sonde lambda — Banc 1 régulation mélange',

  // ── C-codes supplémentaires ──────────────────────────────────────────────────
  C0044: 'Capteur vitesse roue AR droite — Circuit ouvert',
  C0050: 'Capteur vitesse roue AR gauche — Circuit ouvert',
  C0072: 'Moteur pompe ABS — Court-circuit B+',
  C0099: 'Capteur lacet — Circuit incompatible',
  C0125: 'Capteur freinage — Plage haute',
  C0126: 'Capteur freinage — Plage basse',
  C0140: 'Voyant trajectoire — Défaut',
  C0244: 'Tension alimentation ABS — Plage',
  C0270: 'Capteur frein arrière — Performance',
  C0300: 'Module direction assistée — Communication',
  C0710: 'Capteur direction — Plage performance',
  C0800: 'Tension alimentation — Hors limites',
  C0810: 'Capteur entrée — Court-circuit masse',
  C1014: 'ABS Solénoïde — Apprentissage défaut',
  C1015: 'ABS — Pression accumulateur défaut',
  C1018: 'ABS — Voyant alimentation tension',
  C1095: 'Moteur pompe ABS — Circuit court-circuit B+',
  C1130: 'Capteur freinage électronique — Plage performance',
  C1146: 'Capteur angle volant — Plage performance',
  C1185: 'Frein de stationnement électrique — Calibration',
  C1186: 'Frein de stationnement électrique — Moteur défaut',
  C1196: 'Capteur freinage — Désaccord',
  C1206: 'Capteur lacet — Calibrage requis',
  C1245: 'Capteur freinage — Apprentissage non terminé',
  C1284: 'EPS — Calibration moteur défaut',
  C1290: 'EPS — Tension alimentation faible',
  C1295: 'EPS — Surchauffe',
  C1530: 'EPS — Communication bus CAN',
  C1554: 'EPS — Capteur position rotor',
  C1632: 'TPMS — Capteur AV gauche pile faible',
  C1633: 'TPMS — Capteur AV droit pile faible',
  C1634: 'TPMS — Capteur AR gauche pile faible',
  C1635: 'TPMS — Capteur AR droit pile faible',
  C1745: 'BV — Solénoïde SS1 court-circuit',
  C2110: 'Frein de stationnement — Moteur défaut',
  C2120: 'Frein de stationnement — Capteur position',
  C2204: 'TPMS — Apprentissage des capteurs requis',
  C2206: 'TPMS — Apprentissage capteur AV gauche',
  C2207: 'TPMS — Apprentissage capteur AV droit',
  C2208: 'TPMS — Apprentissage capteur AR gauche',
  C2209: 'TPMS — Apprentissage capteur AR droit',

  // ── B-codes supplémentaires (corps/airbag/confort) ───────────────────────────
  B0014: 'Airbag conducteur 2e étage — Circuit',
  B0015: 'Airbag passager 2e étage — Circuit',
  B0022: 'Prétensionneur ceinture AR gauche — Défaut',
  B0023: 'Prétensionneur ceinture AR droit — Défaut',
  B0040: 'Airbag genoux conducteur — Défaut',
  B0041: 'Airbag genoux passager — Défaut',
  B0042: 'Capteur impact avant gauche — Circuit',
  B0043: 'Capteur impact avant droit — Circuit',
  B0050: 'Configuration airbag — Variant incorrect',
  B0053: 'Système retenue — Position siège conducteur',
  B0058: 'Détection occupant passager — Capteur défaut',
  B1015: 'Capteur évaporateur clim — Court-circuit masse',
  B1016: 'Capteur évaporateur clim — Court-circuit alim',
  B1050: 'BSI — Communication multiplexée perdue',
  B1100: 'Module éclairage — Défaut communication',
  B1101: 'Phare AV gauche — Tension haute',
  B1102: 'Phare AV droit — Tension haute',
  B1200: 'Lève-vitre conducteur — Moteur défaut',
  B1201: 'Lève-vitre passager — Moteur défaut',
  B1202: 'Lève-vitre AR gauche — Moteur défaut',
  B1203: 'Lève-vitre AR droit — Moteur défaut',
  B1300: 'Capteur pluie — Circuit',
  B1310: 'Capteur luminosité — Circuit',
  B1325: 'Tension batterie 12V — Hors plage',
  B1335: 'Capteur niveau carburant — Circuit',
  B1370: 'Module siège conducteur — Mémoire',
  B1390: 'Antenne immobiliseur — Circuit',
  B1421: 'Verrouillage centralisé — Défaut moteur',
  B1450: 'Sirène alarme — Circuit',
  B1510: 'Compte-tours — Circuit défaut',
  B1525: 'Voyant tableau de bord — Court-circuit',
  B1550: 'Buzzer combiné — Circuit',
  B1560: 'Capteur niveau lave-glace — Circuit',
  B1604: 'Module radio — Mémoire défaut',
  B1700: 'Allumage clé — Détection défaut',
  B2275: 'Module siège chauffant — Circuit',
  B2293: 'Module rétroviseur — Communication',
  B2392: 'Toit ouvrant — Moteur défaut',
  B2614: 'Antibrouillard AV — Circuit défaut',
  B2620: 'Antibrouillard AR — Circuit défaut',
  B2700: 'Capteur ouverture coffre — Circuit',
  B2960: 'Module antidémarrage — Erreur signature',

  // ── U-codes supplémentaires ──────────────────────────────────────────────────
  U0003: 'Bus CAN haute vitesse — Off',
  U0004: 'Bus CAN haute vitesse — Tension faible',
  U0005: 'Bus CAN haute vitesse — Tension élevée',
  U0006: 'Bus CAN haute vitesse — Câble + ouvert',
  U0007: 'Bus CAN haute vitesse — Câble + faible',
  U0008: 'Bus CAN haute vitesse — Câble + élevé',
  U0009: 'Bus CAN haute vitesse — Câble + court-circuit -',
  U0011: 'Bus CAN moyenne vitesse — Off',
  U0029: 'Bus CAN basse vitesse — Câble + ouvert',
  U0102: 'Perte communication module transfert',
  U0104: 'Perte communication régulateur croisière',
  U0107: 'Perte communication actionneur papillon',
  U0109: 'Perte communication pompe carburant',
  U0110: 'Perte communication moteur entraînement',
  U0115: 'Perte communication module ECM (2)',
  U0118: 'Perte communication module Climat (2)',
  U0123: 'Perte communication capteur lacet',
  U0124: 'Perte communication capteur accélération',
  U0128: 'Perte communication module frein parking',
  U0129: 'Perte communication frein hydraulique',
  U0131: 'Perte communication direction assistée',
  U0136: 'Perte communication module 4 roues motrices',
  U0141: 'Perte communication BCM module 2',
  U0142: 'Perte communication BCM module 3',
  U0152: 'Perte communication module airbag passager',
  U0156: 'Perte communication panneau infos affichage',
  U0159: 'Perte communication module pare-brise',
  U0160: 'Perte communication module siège',
  U0162: 'Perte communication module antibrouillard',
  U0168: 'Perte communication module immobiliseur 2',
  U0170: 'Perte communication module retenue 2',
  U0186: 'Perte communication système audio amplificateur',
  U0194: 'Perte communication module radio satellite',
  U0197: 'Perte communication module téléphone',
  U0212: 'Perte communication module direction',
  U0245: 'Perte communication contrôle voiture',
  U0246: 'Perte communication console centrale',
  U0249: 'Perte communication module électrique siège passager',
  U0254: 'Perte communication module assistance parking',
  U0258: 'Perte communication module commande crash',
  U0273: 'Perte communication module pression pneus',
  U0291: 'Perte communication module détection collision',
  U0300: 'Désaccord configuration logicielle interne',
  U0302: 'Désaccord configuration logicielle BV',
  U0303: 'Désaccord configuration logicielle module transfert',
  U0305: 'Désaccord configuration logicielle régulation croisière',
  U0306: 'Désaccord configuration logicielle carburant',
  U0309: 'Désaccord configuration logicielle système suspension',
  U0316: 'Désaccord configuration logicielle traction 4 roues',
  U0322: 'Désaccord configuration logicielle BCM',
  U0327: 'Désaccord configuration logicielle module détecteur sortie',
  U0400: 'Données invalides reçues — Module générique',
  U0403: 'Données invalides reçues — Régulateur croisière',
  U0405: 'Données invalides reçues — Régulateur ralenti',
  U0406: 'Données invalides reçues — Pression réfrigérant',
  U0407: 'Données invalides reçues — Position pédale accélérateur',
  U0408: 'Données invalides reçues — Hauteur véhicule',
  U0409: 'Données invalides reçues — Niveau carburant',
  U0410: 'Données invalides reçues — Câble alimentation 12V batterie',
  U0411: 'Données invalides reçues — Module ECM (2)',
  U0413: 'Données invalides reçues — Régulateur croisière (2)',
  U0414: 'Données invalides reçues — Régulateur croisière (3)',
  U0416: 'Données invalides reçues — VDC/ESP',
  U0419: 'Données invalides reçues — EPS direction',
  U0420: 'Données invalides reçues — Module 4 roues',
  U0423: 'Données invalides reçues — Combiné instrument',
  U0424: 'Données invalides reçues — Module climat',
  U0425: 'Données invalides reçues — Module airbag',
  U0426: 'Données invalides reçues — Module immobiliseur',
  U0428: 'Données invalides reçues — Capteur direction',
  U2000: 'Bus communication audio — Défaut',
  U2001: 'Bus communication audio — Off',
  U2100: 'CAN initialisation impossible',
  U2105: 'CAN — Pas de communication avec ECM',
  U2106: 'CAN — Pas de communication avec TCM',
  U2107: 'CAN — Pas de communication avec BCM',
  U2108: 'CAN — Pas de communication avec ABS',
  U2110: 'CAN — Pas de communication avec airbag',
  U2120: 'CAN — Pas de communication avec EPS',
  U2150: 'Bus série SCP — Défaut communication',
  U2151: 'Bus série SCP — Off',
  U2152: 'Bus série SCP — Tension faible',

  // ═══════════════════════════════════════════════════════════════════════════
  // ── STELLANTIS (PSA + Fiat + Opel + Jeep) — codes spécifiques ─────────────
  // ═══════════════════════════════════════════════════════════════════════════
  // PSA Peugeot/Citroën (mappés depuis DF codes Diagbox)
  P0470: 'PSA HDi — Capteur pression échappement défaut',
  P0471: 'PSA HDi — Pression échappement hors plage',
  P0472: 'PSA HDi — Pression échappement signal faible',
  P0473: 'PSA HDi — Pression échappement signal élevé',
  P0488: 'PSA HDi — Actionneur EGR position défaut',
  P0489: 'PSA HDi — Vanne EGR circuit faible',
  P0492: 'PSA — Pompe air sec banc 2 débit insuffisant',
  P1112: 'PSA — Capteur temp. air admission B1 court-circuit masse',
  P1113: 'PSA — Capteur temp. air admission B1 court-circuit +',
  P1130: 'PSA — Régulation richesse banc 1 limite supérieure',
  P1133: 'PSA — Régulation richesse banc 1 limite inférieure',
  P1166: 'PSA — Régulation lambda banc 1 amplitude excessive',
  P1167: 'PSA — Régulation lambda banc 1 limite riche',
  P1190: 'PSA — Pression carburant rail incohérence',
  P1191: 'PSA — Pression carburant rail trop basse au démarrage',
  P1330: 'PSA — Régime moteur incohérent capteurs',
  P1335: 'PSA — Capteur PMH/AAC désynchronisation',
  P1339: 'PSA — Apprentissage cible capteur PMH non effectué',
  P1377: 'PSA — Apprentissage anti-ratés non effectué',
  P1378: 'PSA — Anti-ratés cylindre déséquilibré',
  P1390: 'PSA HDi — Capteur AAC court-circuit masse',
  P1391: 'PSA HDi — Capteur AAC court-circuit +',
  P1392: 'PSA HDi — Capteur AAC signal absent',
  P1397: 'PSA — Capteur position arbre à cames "B" intermittent',
  P1413: 'PSA — Pompe air sec banc 1 signal pression faible',
  P1423: 'PSA HDi — Catalyseur SCR conversion NOx insuffisante',
  P1432: 'PSA HDi — Capteur température catalyseur',
  P1440: 'PSA — Capteur fuite EVAP haute tension',
  P1441: 'PSA — EVAP fuite mineure détectée vanne purge',
  P1442: 'PSA — EVAP fuite confirmée canister',
  P1483: 'PSA — Ventilateur haute vitesse défaut',
  P1496: 'PSA — Compresseur clim demande embrayage défaut',
  P1513: 'PSA — Calculateur moteur — Test consistance impossible',
  P1521: 'PSA HDi — Pompe HP carburant alimentation défaut',
  P1522: 'PSA HDi — Régulateur pression carburant alimentation défaut',
  P1538: 'PSA — Régulateur croisière tension circuit',
  P1541: 'PSA — Pompe carburant amorçage défaut',
  P1542: 'PSA — Pompe carburant relais court-circuit',
  P1556: 'PSA — Boîte tronique défaut hydraulique',
  P1564: 'PSA — Boîte tronique pression hydraulique',
  P1567: 'PSA — Régime moteur — coupure activation aux essais',
  P1581: 'PSA — Volet admission position bloquée fermée',
  P1582: 'PSA — Volet admission position bloquée ouverte',
  P1601: 'PSA — Communication interne ECU défaut',
  P1605: 'PSA — Tension batterie 12V régulation défaut',
  P1614: 'PSA — Antidémarrage code clé incorrect',
  P1622: 'PSA — Antidémarrage défaut mémoire',
  P1631: 'PSA — Carte clé pile basse',
  P1632: 'PSA — Carte clé non détectée',
  P1638: 'PSA — Module airbag perte communication',
  P1651: 'PSA — Vitesse roue avant droite référence',
  P1653: 'PSA — Vitesse roue arrière gauche référence',
  P1655: 'PSA — Vitesse roue arrière droite référence',
  P1695: 'PSA — TCM module communication CAN BV',
  P1734: 'PSA — BV5 capteur vitesse turbine plage',
  P1742: 'PSA — BV5 électrovanne pression ligne',
  P1769: 'PSA — BV5 pression de service trop basse',
  P1789: 'PSA — BV5 électrovanne EVS3 défaut',

  // FAP/AdBlue Stellantis spécifique
  P2002_FR: 'Stellantis — FAP saturé régénération impossible',
  P2042: 'Stellantis — Capteur température réservoir AdBlue défaut',
  P2049: 'Stellantis — Doseur AdBlue défaut activation',
  P2078: 'Stellantis — Capteur température FAP entrée plage',
  P2084: 'Stellantis — Capteur température FAP sortie plage',
  P2090: 'Stellantis — Vanne EGR position actionneur défaut',
  P2456: 'Stellantis — Sonde lambda post-FAP signal absent',
  P2457: 'Stellantis — Sonde lambda post-FAP régulation',
  P2460: 'Stellantis — Régénération FAP en mode dégradé',
  P246E: 'Stellantis — Capteur NOx post-SCR défaut alimentation',
  P247A: 'Stellantis — Catalyseur SCR efficacité conversion NOx',
  P249D: 'Stellantis — Réservoir AdBlue presque vide',
  P249E: 'Stellantis — Pompe AdBlue défaut hydraulique',
  P249F: 'Stellantis — Pompe AdBlue surconsommation électrique',
  P20E8: 'Stellantis — Pression réservoir AdBlue trop basse',
  P20EE: 'Stellantis — Concentration AdBlue incorrecte',
  P207F: 'Stellantis — Qualité AdBlue dégradée',
  P204F: 'Stellantis — Réservoir AdBlue détection vide',

  // Fiat / Alfa Romeo spécifique
  P1107: 'Fiat — Capteur baromètre signal faible',
  P1108: 'Fiat — Capteur baromètre signal élevé',
  P1118: 'Fiat — Capteur température air admission incohérence',
  P1186: 'Fiat — Régulation richesse au démarrage défaut',
  P1207: 'Fiat — Circuit injecteur 7 alimentation',
  P1208: 'Fiat — Circuit injecteur 8 alimentation',
  P1217: 'Fiat — Capteur position embrayage défaut',
  P1233: 'Fiat — Pompe carburant désactivée par sécurité',
  P1245: 'Fiat — Régulateur tension alternateur défaut',
  P1278: 'Fiat — Régulation pression turbo limite supérieure',
  P1463: 'Fiat — Pompe canister défaut activation',
  P1507: 'Fiat — IAC valve apprentissage non effectué',
  P1573: 'Fiat — Frein de stationnement signal incohérent',
  P1604: 'Fiat — CKP/CMP désynchronisation pendant démarrage',

  // Opel / Vauxhall spécifique
  P1106: 'Opel — Capteur MAP plage haute',
  P1109: 'Opel — Capteur MAP changement rapide hors limites',
  P1120: 'Opel — Capteur papillon plage performance',
  P1295: 'Opel — Capteur cliquetis 2 plage',
  P1482: 'Opel — Ventilateur moyenne vitesse circuit défaut',
  P1499: 'Opel — Niveau liquide refroidissement bas',
  P1530: 'Opel — Régulateur croisière demande désactivation',
  P1607: 'Opel — Communication PCM avec ABS perdue',
  P1635: 'Opel — Tension 5V référence A circuit',
  P1639: 'Opel — Tension 5V référence B circuit',
  P1860: 'Opel — TCC PWM solenoid circuit',

  // ═══════════════════════════════════════════════════════════════════════════
  // ── VAG (VW + Audi + Skoda + Seat + Porsche) — codes spécifiques ──────────
  // ═══════════════════════════════════════════════════════════════════════════
  P0087: 'VAG — Pression rail/système carburant trop basse',
  P0088: 'VAG — Pression rail/système carburant trop élevée',
  P0089: 'VAG — Régulateur pression carburant performance',
  P0096: 'VAG — Capteur IAT2 plage performance',
  P0238_VAG: 'VAG — Capteur pression suralim plage haute (alias)',
  P0299_VAG: 'VAG — Suralimentation turbo plage insuffisante',
  P0420_VAG: 'VAG — Catalyseur efficacité B1 dégradée',
  P1112_VAG: 'VAG — Capteur IAT B1 plage performance',
  P1117_VAG: 'VAG — Sonde lambda chauffage B1S1 court-circuit B+',
  P1118_VAG: 'VAG — Sonde lambda chauffage B1S2 court-circuit masse',
  P1119_VAG: 'VAG — Sonde lambda chauffage B1S2 court-circuit B+',
  P1120_VAG: 'VAG — Position papillon plage performance',
  P1136_VAG: 'VAG — Boucle fermée B1 régulation pauvre limite',
  P1137_VAG: 'VAG — Boucle fermée B1 régulation riche limite',
  P1138_VAG: 'VAG — Boucle fermée B2 régulation pauvre limite',
  P1144: 'VAG — Capteur MAF résistance plage performance',
  P1145: 'VAG — Capteur MAF résistance court-circuit masse',
  P1146: 'VAG — Capteur MAF résistance court-circuit +',
  P1164: 'VAG — Capteur température carburant signal élevé',
  P1196_VAG: 'VAG — Sonde lambda B1S1 résistance chauffage hors plage',
  P1213_VAG: 'VAG — Injecteur cyl. 1 court-circuit B+ (TDI)',
  P1214_VAG: 'VAG — Injecteur cyl. 2 court-circuit B+ (TDI)',
  P1215_VAG: 'VAG — Injecteur cyl. 3 court-circuit B+ (TDI)',
  P1216_VAG: 'VAG — Injecteur cyl. 4 court-circuit B+ (TDI)',
  P1218: 'VAG — Injecteur cyl. 6 court-circuit B+',
  P1250: 'VAG — Niveau carburant détection plage performance',
  P1287: 'VAG — Vanne de décharge turbo bloquée',
  P1288: 'VAG — Capteur position vanne turbo plage',
  P1289: 'VAG — Capteur position vanne turbo court-circuit',
  P1290: 'VAG — Vanne dump valve bloquée fermée',
  P1297: 'VAG — Connexion turbo/papillon — fuite détectée',
  P1298: 'VAG — Régulation pression suralim plage',
  P1299: 'VAG — Régulation pression suralim trop élevée',
  P1300: 'VAG — Ratés détectés — coupure injection',
  P1325_VAG: 'VAG — Cliquetis cyl. 1 régulation limite',
  P1326: 'VAG — Cliquetis cyl. 2 régulation limite',
  P1327: 'VAG — Cliquetis cyl. 3 régulation limite',
  P1328: 'VAG — Cliquetis cyl. 4 régulation limite',
  P1329: 'VAG — Cliquetis cyl. 5 régulation limite',
  P1340_VAG: 'VAG — Position CKP/CMP désaccord allumage',
  P1386: 'VAG — Module contrôle moteur — Test interne défaut',
  P1394: 'VAG — Bobine d\'allumage cyl. 2 sortie primaire',
  P1395: 'VAG — Bobine d\'allumage cyl. 3 sortie primaire',
  P1396: 'VAG — Bobine d\'allumage cyl. 4 sortie primaire',
  P1398: 'VAG — Bobine d\'allumage cyl. 6 sortie primaire',
  P1418: 'VAG — Pompe air sec relais alimentation',
  P1425: 'VAG — Vanne purge EVAP tension faible',
  P1426: 'VAG — Vanne purge EVAP tension élevée',
  P1433: 'VAG — Pompe air sec relais ouvert',
  P1435: 'VAG — Pompe air sec circuit ouvert',
  P1436: 'VAG — Pompe air sec court-circuit B+',
  P1442_VAG: 'VAG — Vanne fuite EVAP détection capteur',
  P1471_VAG: 'VAG — Pompe diagnostic EVAP fuite circuit',
  P1473: 'VAG — Pompe diagnostic EVAP court-circuit B+',
  P1476: 'VAG — Pompe diagnostic EVAP circuit ouvert',
  P1477: 'VAG — Pompe diagnostic EVAP court-circuit masse',
  P1485: 'VAG — Vanne sortie EVAP plage performance',
  P1500_VAG: 'VAG — Relais pompe carburant tension circuit',
  P1501: 'VAG — Relais pompe carburant court-circuit masse',
  P1502: 'VAG — Relais pompe carburant court-circuit +',
  P1543: 'VAG — Capteur position papillon B circuit faible',
  P1544: 'VAG — Capteur position papillon B circuit élevé',
  P1545_VAG: 'VAG — Position papillon plage performance',
  P1546_VAG: 'VAG — Position papillon mode dégradé',
  P1547: 'VAG — Vanne dump turbo court-circuit masse',
  P1548: 'VAG — Vanne dump turbo court-circuit +',
  P1554: 'VAG — Idle stabilisation hors limites',
  P1557: 'VAG — Régulation pression turbo limite positive',
  P1559: 'VAG — Régulation papillon — Apprentissage limite',
  P1568: 'VAG — Régulation EGR limite tolérance haute',
  P1602_VAG: 'VAG — Tension alimentation B+ trop basse',
  P1603_VAG: 'VAG — ECM/PCM performance interne',
  P1612_VAG: 'VAG — Codage ECU défaut',
  P1615: 'VAG — Voyant MIL circuit ouvert',
  P1721: 'VAG — TCM tension batterie trop basse',
  P1731: 'VAG — Apprentissage point embrayage non effectué',
  P1739: 'VAG — Solenoide pression — Court-circuit',
  P1740: 'VAG — Boîte tronique — Variateur primaire défaut',
  P1741: 'VAG — Boîte tronique — Pression hydraulique secondaire',
  P1743: 'VAG — Embrayage convertisseur fermé',

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Groupe Renault (Renault + Dacia + Alpine + Nissan Alliance) ───────────
  // ═══════════════════════════════════════════════════════════════════════════
  P0089_RNT: 'Renault — Régulateur pression carburant performance HP',
  P0090_RNT: 'Renault — Régulateur pression carburant circuit',
  P0093_RNT: 'Renault — Fuite système carburant détectée',
  P0095_RNT: 'Renault — Capteur IAT2 circuit',
  P0234_RNT: 'Renault — Turbo suralim trop élevée régulation',
  P0299_RNT: 'Renault — Turbo suralim sous-pression détectée',
  P0380_RNT: 'Renault — Préchauffage défaut alimentation calculateur',
  P0381_RNT: 'Renault — Préchauffage voyant tension défaut',
  P0420_RNT: 'Renault — Catalyseur efficacité insuffisante (DF093)',
  P0490_RNT: 'Renault — Vanne EGR circuit défaut (DF131)',
  P0500_RNT: 'Renault — Capteur vitesse véhicule défaut (DF005)',
  P0571_RNT: 'Renault — Contacteur pédale frein circuit',
  P0606_RNT: 'Renault — Calculateur moteur défaut processeur (DF048)',
  P1100_RNT: 'Renault — MAF signal intermittent (DF002)',
  P1101_RNT: 'Renault — Boucle régulation richesse limite',
  P1111: 'Renault — Géométrie variable turbo apprentissage',
  P1115_RNT: 'Renault — Capteur eau dans gazole circuit (DF155)',
  P1141_RNT: 'Renault — Charge moteur calculée incohérente',
  P1142_RNT: 'Renault — Charge moteur signal incohérent',
  P1147: 'Renault — Vanne EGR by-pass refroidisseur défaut',
  P1148: 'Renault — Pompe injection HP régulation pression',
  P1149: 'Renault — Pression rail HP régulation limite',
  P1151: 'Renault — Régulation richesse cylindres déséquilibre',
  P1160: 'Renault — Régulation cylindre 1 contribution',
  P1161: 'Renault — Régulation cylindre 2 contribution',
  P1162_RNT: 'Renault — Régulation cylindre 3 contribution',
  P1163: 'Renault — Régulation cylindre 4 contribution',
  P1199: 'Renault — Capteur niveau liquide refroidissement',
  P1236: 'Renault — Pompe carburant régulation pression',
  P1238: 'Renault — Injecteur défaut alimentation',
  P1239: 'Renault — Vanne pompe carburant régulation',
  P1240: 'Renault — Injecteur cyl. 1 alimentation défaut',
  P1241: 'Renault — Injecteur cyl. 2 alimentation défaut',
  P1242: 'Renault — Injecteur cyl. 3 alimentation défaut',
  P1243: 'Renault — Injecteur cyl. 4 alimentation défaut',
  P1244: 'Renault — Apprentissage injecteur en cours',
  P1336_RNT: 'Renault — Apprentissage rendement vilebrequin (DF080)',
  P1339_RNT: 'Renault — Apprentissage position PMH incomplet',
  P1383_RNT: 'Renault — Bobine allumage primaire défaut',
  P1410_RNT: 'Renault — Vanne EGR position ouverte (DF132)',
  P1416: 'Renault — Vanne décharge turbo défaut',
  P1430_RNT: 'Renault — Détection fuite EVAP capteur',
  P1450_RNT: 'Renault — Pression vapeurs EVAP hors plage',
  P1456: 'Renault — Catalyseur amorçage température',
  P1471_RNT: 'Renault — Pompe diagnostic EVAP circuit',
  P1490_RNT: 'Renault — Pompe air sec pression non détectée',
  P1500_RNT: 'Renault — Pompe carburant tension régulation (DF169)',
  P1509: 'Renault — Régulateur ralenti — Stabilité',
  P1531_RNT: 'Renault — Régulateur croisière bouton défaut',
  P1540_RNT: 'Renault — Régulateur croisière mode désactivé sécurité',
  P1571_RNT: 'Renault — Frein demande désactivation régulateur',
  P1599_RNT: 'Renault — Limite couple moteur demande BV (DF158)',
  P1600_RNT: 'Renault — Module immobiliseur PCM communication',
  P1602_RNT: 'Renault — Module immobiliseur pas de réponse',
  P1652_RNT: 'Renault — Vitesse roue référence (DF170)',
  P1735: 'Renault — BV tronique électrovanne A circuit',
  P1736: 'Renault — BV tronique électrovanne B circuit',
  P1737: 'Renault — BV tronique pression hydraulique',
  P1738_RNT: 'Renault — BV capteur vitesse turbine plage',
  P1745_RNT: 'Renault — BV pression hydraulique défaut',
  P1747_RNT: 'Renault — BV solénoïde régulation pression',
  P1762_RNT: 'Renault — BV solénoïde 2-3 défaut',
  P1816: 'Renault — TCM/BV — Demande couple ECU',
  P1820: 'Renault — BV mode dégradé activé',
  P2096_RNT: 'Renault — Sonde post-cat mélange trop pauvre',
  P2097_RNT: 'Renault — Sonde post-cat mélange trop riche',

  // Codes spécifiques Renault dCi (diesel)
  P2226: 'Renault dCi — Capteur baromètre signal incohérent',
  P2227: 'Renault dCi — Capteur baromètre plage performance',
  P2228_RNT: 'Renault dCi — Capteur baromètre signal trop faible',
  P2229_RNT: 'Renault dCi — Capteur baromètre signal trop élevé',
  P226C: 'Renault dCi — Capteur pression turbo plage',
  P227A: 'Renault dCi — Capteur pression baromètre intermittent',
  P2452_RNT: 'Renault dCi — Capteur pression FAP entrée',
  P2453_RNT: 'Renault dCi — Capteur pression FAP sortie',
  P2454_RNT: 'Renault dCi — Capteur pression différentielle FAP basse',
  P2455_RNT: 'Renault dCi — Capteur pression différentielle FAP haute',
  P2458_RNT: 'Renault dCi — Régénération FAP — durée excessive',
  P2459_RNT: 'Renault dCi — Régénération FAP — fréquence excessive',
  P2463_RNT: 'Renault dCi — FAP saturé suies',
  P2464_RNT: 'Renault dCi — FAP température entrée plage',
  P246C_RNT: 'Renault dCi — FAP système — défaut détecté',
  P247A_RNT: 'Renault dCi — Catalyseur SCR conversion NOx',
  P249D_RNT: 'Renault dCi — Réservoir AdBlue niveau bas',

  // Codes Nissan (alliance avec Renault)
  P1078: 'Nissan — Capteur VVT-i position avance',
  P1212: 'Nissan — ABS communication TCS perdue',
  P1320: 'Nissan — Allumage primaire défaut',
  P1444: 'Nissan — Vanne purge canister volume insuffisant',
}
