export type OBDConnectionType = 'wifi' | 'bluetooth' | 'usb'
export type OBDConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'error'

export interface OBDParameter {
  pid: string
  name: string
  value: number | string | null
  unit: string
  group: 'engine' | 'fuel' | 'electric' | 'exhaust' | 'diag' | 'hybrid' | 'turbo'
  raw?: string
}

export interface OBDFaultCode {
  code: string
  description: string
  system: 'powertrain' | 'chassis' | 'body' | 'network'
  severity: 'low' | 'medium' | 'high'
  pending?: boolean
  module?: string
}

export interface ReadinessMonitor {
  name: string
  supported: boolean
  ready: boolean
}

export interface OBDScanResult {
  timestamp: string
  connectionType: OBDConnectionType
  deviceName?: string
  faultCodes: OBDFaultCode[]
  parameters: OBDParameter[]
  readiness?: ReadinessMonitor[]
  vin?: string
  milOn?: boolean
  dtcCount?: number
  protocolUsed?: string
}

export interface OBDScannerState {
  status: OBDConnectionStatus
  connectionType: OBDConnectionType | null
  deviceName: string | null
  error: string | null
  scanResult: OBDScanResult | null
  isScanning: boolean
  scanStep?: string
}

// PIDs Mode 01 — couverture complète SAE J1979 + extensions diesel/hybride/turbo
export const OBD_PIDS = {
  // ── Moteur ────────────────────────────────────────────────────────────────────
  RPM:               { pid: '010C', name: 'Régime moteur',                    unit: 'tr/min', group: 'engine' as const },
  SPEED:             { pid: '010D', name: 'Vitesse',                          unit: 'km/h',   group: 'engine' as const },
  ENGINE_LOAD:       { pid: '0104', name: 'Charge moteur',                    unit: '%',      group: 'engine' as const },
  ABS_LOAD:          { pid: '0143', name: 'Charge absolue moteur',            unit: '%',      group: 'engine' as const },
  COOLANT_TEMP:      { pid: '0105', name: 'Temp. liquide refroidissement',    unit: '°C',     group: 'engine' as const },
  OIL_TEMP:          { pid: '015C', name: 'Temp. huile moteur',               unit: '°C',     group: 'engine' as const },
  INTAKE_TEMP:       { pid: '010F', name: 'Temp. air admission',              unit: '°C',     group: 'engine' as const },
  AMBIENT_TEMP:      { pid: '0146', name: 'Temp. extérieure',                 unit: '°C',     group: 'engine' as const },
  TIMING:            { pid: '010E', name: 'Avance allumage',                  unit: '°',      group: 'engine' as const },
  MAP:               { pid: '010B', name: 'Pression admission (MAP)',         unit: 'kPa',    group: 'engine' as const },
  MAF:               { pid: '0110', name: 'Débit air massique (MAF)',         unit: 'g/s',    group: 'engine' as const },
  RUN_TIME:          { pid: '011F', name: 'Temps moteur actif',               unit: 's',      group: 'engine' as const },
  THROTTLE_REL:      { pid: '0145', name: 'Position papillon relative',       unit: '%',      group: 'engine' as const },
  THROTTLE_B:        { pid: '0147', name: 'Position papillon B',              unit: '%',      group: 'engine' as const },
  ACCEL_PEDAL_D:     { pid: '0149', name: 'Position pédale accélérateur D',   unit: '%',      group: 'engine' as const },
  ACCEL_PEDAL_E:     { pid: '014A', name: 'Position pédale accélérateur E',   unit: '%',      group: 'engine' as const },
  COMMANDED_THROTTLE:{ pid: '014C', name: 'Papillon commandé',                unit: '%',      group: 'engine' as const },
  TORQUE_DEMAND:     { pid: '0161', name: 'Couple moteur demandé',            unit: '%',      group: 'engine' as const },
  TORQUE_ACTUAL:     { pid: '0162', name: 'Couple moteur réel',               unit: '%',      group: 'engine' as const },
  TORQUE_REF:        { pid: '0163', name: 'Couple moteur référence',          unit: 'Nm',     group: 'engine' as const },
  ENGINE_TORQUE_PCT: { pid: '0164', name: 'Couple % données moteur',          unit: '%',      group: 'engine' as const },

  // ── Carburant ─────────────────────────────────────────────────────────────────
  STFT_B1:           { pid: '0106', name: 'Correction CT carburant Banc 1',   unit: '%',      group: 'fuel' as const },
  LTFT_B1:           { pid: '0107', name: 'Correction LT carburant Banc 1',   unit: '%',      group: 'fuel' as const },
  STFT_B2:           { pid: '0108', name: 'Correction CT carburant Banc 2',   unit: '%',      group: 'fuel' as const },
  LTFT_B2:           { pid: '0109', name: 'Correction LT carburant Banc 2',   unit: '%',      group: 'fuel' as const },
  FUEL_PRESSURE:     { pid: '010A', name: 'Pression carburant (rail)',        unit: 'kPa',    group: 'fuel' as const },
  FUEL_PRESSURE_ABS: { pid: '0123', name: 'Pression rail absolue (HP)',       unit: 'kPa',    group: 'fuel' as const },
  FUEL_LEVEL:        { pid: '012F', name: 'Niveau réservoir carburant',       unit: '%',      group: 'fuel' as const },
  FUEL_RATE:         { pid: '015E', name: 'Consommation instantanée',         unit: 'L/h',    group: 'fuel' as const },
  FUEL_TYPE:         { pid: '0151', name: 'Type carburant',                   unit: '',       group: 'fuel' as const },
  ETHANOL_PCT:       { pid: '0152', name: 'Pourcentage éthanol',              unit: '%',      group: 'fuel' as const },
  EQUIV_RATIO:       { pid: '0144', name: 'Ratio air/carburant commandé',     unit: 'λ',      group: 'fuel' as const },
  FUEL_SYSTEM_STATUS:{ pid: '0103', name: 'État système carburant',           unit: '',       group: 'fuel' as const },

  // ── Turbo / suralimentation ───────────────────────────────────────────────────
  BOOST_PRESSURE:    { pid: '0170', name: 'Pression de suralimentation',      unit: 'kPa',    group: 'turbo' as const },
  BOOST_COMMANDED:   { pid: '0172', name: 'Pression turbo commandée',         unit: 'kPa',    group: 'turbo' as const },
  TURBO_INLET_TEMP:  { pid: '0174', name: 'Temp. entrée turbo',               unit: '°C',     group: 'turbo' as const },
  TURBO_OUTLET_TEMP: { pid: '0175', name: 'Temp. sortie turbo',               unit: '°C',     group: 'turbo' as const },
  TURBO_RPM:         { pid: '0176', name: 'Régime turbo',                     unit: 'tr/min', group: 'turbo' as const },
  CHARGE_AIR_TEMP:   { pid: '0177', name: 'Temp. air après refroidisseur',    unit: '°C',     group: 'turbo' as const },

  // ── Électrique ────────────────────────────────────────────────────────────────
  THROTTLE:          { pid: '0111', name: 'Position papillon',                unit: '%',      group: 'electric' as const },
  BATTERY:           { pid: '0142', name: 'Tension batterie 12V',             unit: 'V',      group: 'electric' as const },
  BARO:              { pid: '0133', name: 'Pression atmosphérique',           unit: 'kPa',    group: 'electric' as const },
  CONTROL_MODULE_V:  { pid: '0142', name: 'Tension module contrôle',          unit: 'V',      group: 'electric' as const },

  // ── Échappement / Émissions ───────────────────────────────────────────────────
  O2_B1S1_VOLT:      { pid: '0114', name: 'Sonde O2 Banc1-Sonde1 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B1S2_VOLT:      { pid: '0115', name: 'Sonde O2 Banc1-Sonde2 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B2S1_VOLT:      { pid: '0118', name: 'Sonde O2 Banc2-Sonde1 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_B2S2_VOLT:      { pid: '0119', name: 'Sonde O2 Banc2-Sonde2 (tension)',  unit: 'V',      group: 'exhaust' as const },
  O2_WIDE_B1S1:      { pid: '0134', name: 'Lambda large bande B1S1',          unit: 'λ',      group: 'exhaust' as const },
  CATALYST_TEMP_B1S1:{ pid: '013C', name: 'Temp. catalyseur B1 Sonde1',       unit: '°C',     group: 'exhaust' as const },
  CATALYST_TEMP_B2S1:{ pid: '013D', name: 'Temp. catalyseur B2 Sonde1',       unit: '°C',     group: 'exhaust' as const },
  COMMANDED_EGR:     { pid: '012C', name: 'EGR commandé',                     unit: '%',      group: 'exhaust' as const },
  EGR_ERROR:         { pid: '012D', name: 'Erreur EGR',                       unit: '%',      group: 'exhaust' as const },
  COMMANDED_PURGE:   { pid: '012E', name: 'Purge canister commandée',         unit: '%',      group: 'exhaust' as const },
  EVAP_PRESSURE:     { pid: '0132', name: 'Pression vapeurs EVAP',            unit: 'Pa',     group: 'exhaust' as const },
  DPF_INLET_TEMP:    { pid: '017C', name: 'Temp. entrée FAP',                 unit: '°C',     group: 'exhaust' as const },
  DPF_DELTA_PRESS:   { pid: '017A', name: 'Pression différentielle FAP',      unit: 'kPa',    group: 'exhaust' as const },
  NOX_PRE_SCR:       { pid: '0183', name: 'NOx avant SCR',                    unit: 'ppm',    group: 'exhaust' as const },
  ADBLUE_LEVEL:      { pid: '019B', name: 'Niveau AdBlue',                    unit: '%',      group: 'exhaust' as const },

  // ── Hybride / EV ──────────────────────────────────────────────────────────────
  HYBRID_BATT_REM:   { pid: '015B', name: 'Batterie hybride restante',        unit: '%',      group: 'hybrid' as const },

  // ── Diagnostic ────────────────────────────────────────────────────────────────
  MIL_TIME:          { pid: '014D', name: 'Durée voyant MIL allumé',          unit: 'min',    group: 'diag' as const },
  DIST_MIL:          { pid: '0121', name: 'Distance avec MIL allumé',         unit: 'km',     group: 'diag' as const },
  DIST_CLEAR:        { pid: '0131', name: 'Distance depuis effacement',       unit: 'km',     group: 'diag' as const },
  WARMUPS_CLEAR:     { pid: '0130', name: 'Cycles chauffe depuis reset',      unit: '',       group: 'diag' as const },
  TIME_CLEAR:        { pid: '014E', name: 'Temps depuis reset codes',         unit: 'min',    group: 'diag' as const },
} as const

export const DTC_SYSTEM_MAP: Record<string, OBDFaultCode['system']> = {
  P: 'powertrain',
  C: 'chassis',
  B: 'body',
  U: 'network',
}

// Codes DTC les plus fréquents (~250 entrées) — descriptions en français
export const KNOWN_DTC: Record<string, string> = {
  // ── Moteur / Powertrain (P-codes) ─────────────────────────────────────────────
  P0010: 'Position arbre à cames "A" (banc 1) — Actionneur défaillant',
  P0011: 'Position arbre à cames "A" (banc 1) — Avance excessive',
  P0012: 'Position arbre à cames "A" (banc 1) — Retard excessif',
  P0014: 'Position arbre à cames "B" (banc 1) — Avance excessive',
  P0016: 'Corrélation vilebrequin/arbre à cames banc 1',
  P0017: 'Corrélation vilebrequin/arbre à cames banc 1 (capteur B)',
  P0030: 'Sonde O2 B1S1 — Circuit chauffage défaillant',
  P0036: 'Sonde O2 B1S2 — Circuit chauffage défaillant',
  P0050: 'Sonde O2 B2S1 — Circuit chauffage défaillant',
  P0100: 'Débitmètre d\'air (MAF) — Circuit défaillant',
  P0101: 'Débitmètre d\'air (MAF) — Plage/performance hors limites',
  P0102: 'Débitmètre d\'air (MAF) — Signal trop faible',
  P0103: 'Débitmètre d\'air (MAF) — Signal trop élevé',
  P0105: 'Capteur pression admission (MAP) — Circuit défaillant',
  P0106: 'Capteur MAP — Plage/performance',
  P0107: 'Capteur MAP — Signal trop faible',
  P0108: 'Capteur MAP — Signal trop élevé',
  P0110: 'Capteur température admission — Circuit défaillant',
  P0111: 'Capteur température admission — Plage/performance',
  P0112: 'Capteur température admission — Signal trop faible',
  P0113: 'Capteur température admission — Signal trop élevé',
  P0115: 'Capteur température liquide refroidissement — Circuit défaillant',
  P0116: 'Capteur température LDR — Plage/performance',
  P0117: 'Capteur température LDR — Signal trop faible',
  P0118: 'Capteur température LDR — Signal trop élevé',
  P0120: 'Capteur position papillon (TPS) — Circuit défaillant',
  P0121: 'Capteur TPS — Plage/performance',
  P0122: 'Capteur TPS — Signal trop faible',
  P0123: 'Capteur TPS — Signal trop élevé',
  P0128: 'Liquide refroidissement n\'atteint pas la temp. de régulation',
  P0130: 'Sonde lambda B1S1 — Circuit défaillant',
  P0131: 'Sonde lambda B1S1 — Tension trop faible',
  P0132: 'Sonde lambda B1S1 — Tension trop élevée',
  P0133: 'Sonde lambda B1S1 — Réponse lente',
  P0134: 'Sonde lambda B1S1 — Pas d\'activité détectée',
  P0135: 'Sonde lambda B1S1 — Chauffage défaillant',
  P0136: 'Sonde lambda B1S2 — Circuit défaillant',
  P0140: 'Sonde lambda B1S2 — Pas d\'activité détectée',
  P0141: 'Sonde lambda B1S2 — Chauffage défaillant',
  P0150: 'Sonde lambda B2S1 — Circuit défaillant',
  P0170: 'Système carburant — Réglage hors limites (Banc 1)',
  P0171: 'Système carburant — Mélange trop pauvre (Banc 1)',
  P0172: 'Système carburant — Mélange trop riche (Banc 1)',
  P0173: 'Système carburant — Réglage hors limites (Banc 2)',
  P0174: 'Système carburant — Mélange trop pauvre (Banc 2)',
  P0175: 'Système carburant — Mélange trop riche (Banc 2)',
  P0180: 'Capteur température carburant A — Défaut',
  P0190: 'Pression carburant rail — Circuit défaillant',
  P0191: 'Pression carburant rail — Plage/performance',
  P0192: 'Pression carburant rail — Trop faible',
  P0193: 'Pression carburant rail — Trop élevée',
  P0200: 'Circuit injecteur — Défaut général',
  P0201: 'Injecteur cylindre 1 — Circuit défaillant',
  P0202: 'Injecteur cylindre 2 — Circuit défaillant',
  P0203: 'Injecteur cylindre 3 — Circuit défaillant',
  P0204: 'Injecteur cylindre 4 — Circuit défaillant',
  P0205: 'Injecteur cylindre 5 — Circuit défaillant',
  P0206: 'Injecteur cylindre 6 — Circuit défaillant',
  P0217: 'Surchauffe moteur',
  P0219: 'Sur-régime moteur',
  P0220: 'Capteur position papillon B — Circuit défaillant',
  P0230: 'Pompe à carburant — Circuit défaillant',
  P0234: 'Suralimentation turbo trop élevée',
  P0235: 'Capteur pression suralimentation — Circuit défaillant',
  P0236: 'Capteur pression suralimentation — Plage/performance',
  P0237: 'Capteur pression suralimentation — Signal trop faible',
  P0238: 'Capteur pression suralimentation — Signal trop élevé',
  P0243: 'Wastegate turbo solenoïde A — Défaut',
  P0245: 'Wastegate turbo solenoïde A — Signal trop faible',
  P0299: 'Suralimentation turbo insuffisante (sous-pression)',
  P0300: 'Ratés d\'allumage aléatoires détectés (multi-cylindres)',
  P0301: 'Raté d\'allumage cylindre 1',
  P0302: 'Raté d\'allumage cylindre 2',
  P0303: 'Raté d\'allumage cylindre 3',
  P0304: 'Raté d\'allumage cylindre 4',
  P0305: 'Raté d\'allumage cylindre 5',
  P0306: 'Raté d\'allumage cylindre 6',
  P0307: 'Raté d\'allumage cylindre 7',
  P0308: 'Raté d\'allumage cylindre 8',
  P0315: 'Position vilebrequin — Variation non apprise',
  P0325: 'Capteur cliquetis (knock) banc 1 — Circuit défaillant',
  P0327: 'Capteur cliquetis banc 1 — Signal trop faible',
  P0335: 'Capteur position vilebrequin (CKP) — Circuit défaillant',
  P0336: 'Capteur position vilebrequin — Plage/performance',
  P0340: 'Capteur position arbre à cames (CMP) — Circuit défaillant',
  P0341: 'Capteur position arbre à cames — Plage/performance',
  P0351: 'Bobine d\'allumage A — Défaut primaire/secondaire',
  P0352: 'Bobine d\'allumage B — Défaut primaire/secondaire',
  P0353: 'Bobine d\'allumage C — Défaut primaire/secondaire',
  P0354: 'Bobine d\'allumage D — Défaut primaire/secondaire',
  P0380: 'Préchauffage diesel — Circuit défaillant',
  P0381: 'Préchauffage diesel — Voyant',
  P0400: 'EGR — Débit insuffisant',
  P0401: 'EGR — Débit insuffisant détecté',
  P0402: 'EGR — Débit excessif détecté',
  P0403: 'EGR — Circuit solénoïde défaillant',
  P0404: 'EGR — Plage/performance',
  P0405: 'Capteur position vanne EGR — Signal trop faible',
  P0406: 'Capteur position vanne EGR — Signal trop élevé',
  P0420: 'Catalyseur — Efficacité insuffisante (Banc 1)',
  P0421: 'Catalyseur de démarrage — Efficacité insuffisante (Banc 1)',
  P0430: 'Catalyseur — Efficacité insuffisante (Banc 2)',
  P0440: 'Système évaporation carburant — Défaut général',
  P0441: 'Système EVAP — Purge incorrecte',
  P0442: 'Système EVAP — Petite fuite détectée',
  P0443: 'Vanne purge canister — Circuit défaillant',
  P0446: 'Système EVAP — Vent control circuit',
  P0455: 'Système EVAP — Grosse fuite détectée',
  P0456: 'Système EVAP — Très petite fuite détectée',
  P0480: 'Ventilateur refroidissement 1 — Circuit défaillant',
  P0481: 'Ventilateur refroidissement 2 — Circuit défaillant',
  P0500: 'Capteur vitesse véhicule (VSS) — Défaut',
  P0501: 'Capteur vitesse véhicule — Plage/performance',
  P0505: 'Système ralenti (IAC) — Défaut',
  P0506: 'Régime ralenti trop bas',
  P0507: 'Régime ralenti trop élevé',
  P0560: 'Tension système — Défaut',
  P0562: 'Tension système — Trop faible',
  P0563: 'Tension système — Trop élevée',
  P0600: 'Bus communication série — Défaut interne',
  P0601: 'Module contrôle moteur (ECM) — Erreur mémoire interne',
  P0603: 'Module contrôle moteur — Mémoire KAM perdue',
  P0606: 'Module contrôle moteur — Défaut processeur',
  P0607: 'Module contrôle moteur — Performance',
  P0613: 'TCM — Défaut processeur',
  P0700: 'Système contrôle boîte de vitesses — Défaut général',
  P0715: 'Capteur vitesse entrée/turbine BV — Défaut',
  P0720: 'Capteur vitesse sortie BV — Défaut',
  P0721: 'Capteur vitesse sortie BV — Plage/performance',
  P0725: 'Capteur vitesse moteur — Entrée BV',
  P0730: 'Rapport incorrect détecté (BV)',
  P0731: 'Rapport 1 incorrect',
  P0732: 'Rapport 2 incorrect',
  P0733: 'Rapport 3 incorrect',
  P0734: 'Rapport 4 incorrect',
  P0740: 'Convertisseur de couple — Défaut verrouillage',
  P0741: 'Convertisseur de couple — Performance/coincé',
  P0750: 'Électrovanne BV A — Défaut',
  P0755: 'Électrovanne BV B — Défaut',
  P1000: 'Autodiagnostic en cours (readiness non complété)',
  P1004: 'Système VVT — Performance',
  P1101: 'MAF — Hors plage de fonctionnement',
  P1115: 'Capteur température LDR — Plage performance',
  P1128: 'Boucle fermée — Pas atteinte (banc 1)',
  P1131: 'Mélange trop pauvre banc 1 (apprentissage)',
  P1135: 'Sonde lambda B1S1 — Circuit chauffage',
  P1200: 'Circuit injecteur — Défaut',
  P1336: 'Apprentissage couple — Hors limites',
  P1351: 'Bobine d\'allumage — Tension primaire',
  P1400: 'EGR — Circuit solénoïde',
  P1421: 'Catalyseur AIR — Défaut',
  P1450: 'Pression vapeurs EVAP — Hors plage',
  P1500: 'VSS — Hors plage',
  P1610: 'Module immobiliseur — Défaut',
  P1700: 'TCM — Signal non valide',
  P2000: 'NOx — Catalyseur banc 1',
  P2002: 'Filtre à particules (FAP) — Efficacité hors plage banc 1',
  P2031: 'Capteur température FAP — Défaut',
  P2032: 'Capteur température FAP banc 1 sonde 2 — Signal faible',
  P2033: 'Capteur température FAP banc 1 sonde 2 — Signal élevé',
  P2080: 'Capteur température échappement banc 1 sonde 1 — Plage',
  P2096: 'Sonde post-cat banc 1 — Mélange trop pauvre',
  P2097: 'Sonde post-cat banc 1 — Mélange trop riche',
  P2122: 'Capteur pédale accélérateur D — Signal trop faible',
  P2138: 'Désaccord capteurs pédale D/E',
  P2187: 'Système carburant trop pauvre au ralenti banc 1',
  P2196: 'Sonde lambda B1S1 — Bloquée riche',
  P2197: 'Sonde lambda B1S1 — Bloquée pauvre',
  P2228: 'Capteur pression barométrique — Signal trop faible',
  P2237: 'Sonde lambda B1S1 — Circuit pompage défaut',
  P2261: 'Wastegate turbo — Mécanique bloquée',
  P2262: 'Wastegate turbo — Performance dégradée',
  P2270: 'Sonde lambda B1S2 — Bloquée pauvre',
  P2271: 'Sonde lambda B1S2 — Bloquée riche',
  P2279: 'Fuite d\'air admission',
  P2452: 'Capteur pression différentielle FAP — Circuit',
  P2453: 'Capteur pression différentielle FAP — Plage',
  P2454: 'Capteur pression différentielle FAP — Signal faible',
  P2455: 'Capteur pression différentielle FAP — Signal élevé',
  P2459: 'Régénération FAP — Fréquence excessive',
  P2463: 'FAP — Accumulation suie excessive',
  P244A: 'Pression différentielle FAP — Trop faible',
  P244B: 'Pression différentielle FAP — Trop élevée',
  P246C: 'FAP — Niveau saturation maximum',
  P2563: 'Capteur position turbo — Plage',
  P3000: 'Tension batterie hybride — Hors limites',

  // ── ABS / Châssis (C-codes) ───────────────────────────────────────────────────
  C0020: 'ABS — Défaut général système de freinage',
  C0031: 'Capteur vitesse roue AV gauche — Circuit ouvert',
  C0032: 'Capteur vitesse roue AV gauche — Court-circuit',
  C0033: 'Capteur vitesse roue AV gauche — Signal absent',
  C0034: 'Capteur vitesse roue AV droite — Défaut circuit',
  C0035: 'Capteur vitesse roue AV droite — Circuit ouvert',
  C0036: 'Capteur vitesse roue AV droite — Court-circuit',
  C0037: 'Capteur vitesse roue AV droite — Signal absent',
  C0040: 'Capteur vitesse roue AR droite — Défaut circuit',
  C0041: 'Capteur vitesse roue AR droite — Signal absent',
  C0042: 'Capteur vitesse roue AR droite — Court-circuit',
  C0045: 'Capteur vitesse roue AR gauche — Défaut circuit',
  C0046: 'Capteur vitesse roue AR gauche — Signal absent',
  C0047: 'Capteur vitesse roue AR gauche — Court-circuit',
  C0051: 'Capteur angle volant — Incohérence',
  C0060: 'Actionneur ABS — Défaut circuit',
  C0061: 'Actionneur ABS — Plage performance',
  C0065: 'Électrovanne ABS — Défaut',
  C0070: 'Moteur pompe ABS — Défaut circuit',
  C0071: 'Moteur pompe ABS — Sous-tension',
  C0110: 'Moteur pompe ABS — Défaillance',
  C0113: 'Capteur pression hydraulique — Défaut',
  C0121: 'Relais soupape ABS — Circuit défaillant',
  C0131: 'Capteur pression frein — Défaut',
  C0136: 'Capteur pression frein — Circuit défaillant',
  C0141: 'Solénoïde ABS gauche — Défaut circuit',
  C0148: 'Solénoïde ABS droit — Défaut circuit',
  C0161: 'Contacteur feux stop — Défaut circuit',
  C0162: 'Pédale de frein — Switch défaut',
  C0165: 'Capteur de lacet (ESP) — Défaut circuit',
  C0186: 'Capteur accélération latérale — Défaut',
  C0187: 'Capteur accélération latérale — Signal incohérent',
  C0196: 'Capteur taux de lacet / gyroscope (ESP) — Défaut',
  C0197: 'Capteur taux de lacet — Signal incohérent',
  C0200: 'Capteur accélération longitudinale — Défaut',
  C0210: 'Capteur vitesse transmission — Défaut circuit',
  C0221: 'Capteur vitesse AV droite — Circuit ouvert',
  C0245: 'Fréquence capteur vitesse roue — Erreur',
  C0265: 'Relais ABS — Défaut circuit',
  C0267: 'Moteur pompe ABS — Circuit ouvert / CC',
  C0269: 'Temps de décharge ABS excessif',
  C0281: 'Contacteur pédale de frein — Défaut circuit',
  C0284: 'Module ABS/ESP — Défaut interne',
  C0291: 'Perte communication avec BSI/BCM',
  C0292: 'Perte communication avec ECM',
  C0299: 'Perte communication ESP/VDC',
  C0561: 'ESP désactivé par utilisateur',
  C1000: 'Module ABS — Défaillance interne',
  C1010: 'Solénoïde ABS AV gauche',
  C1011: 'Solénoïde ABS AV droit',
  C1012: 'Solénoïde ABS AR gauche',
  C1013: 'Solénoïde ABS AR droit',
  C1094: 'Moteur pompe ABS — Tension hors limites',
  C1100: 'Moteur pompe ABS — Défaillance',
  C1121: 'Capteur vitesse roue AV gauche — Signal faible',
  C1122: 'Capteur vitesse roue AV droite — Signal faible',
  C1123: 'Capteur vitesse roue AR gauche — Signal faible',
  C1124: 'Capteur vitesse roue AR droite — Signal faible',
  C1145: 'Capteur d\'angle de volant — Défaut',
  C1155: 'Capteur vitesse roue AV gauche — Absence signal',
  C1156: 'Capteur vitesse roue AV droite — Absence signal',
  C1200: 'Capteur pression maître-cylindre — Défaut',
  C1210: 'Voyant ABS — Défaut',
  C1233: 'Capteur vitesse roue AV gauche — Signal absent',
  C1234: 'Capteur vitesse roue AV droite — Signal absent',
  C1235: 'Capteur vitesse roue AR droite — Signal absent',
  C1236: 'Capteur vitesse roue AR gauche — Signal absent',
  C1281: 'Direction assistée — Effort assistance défaut',

  // ── TPMS / Pression pneus (C-codes) ──────────────────────────────────────────
  C2200: 'TPMS — Module défaillant',
  C2202: 'TPMS — Voyant défaut',
  C2210: 'TPMS — Capteur AV gauche absent',
  C2211: 'TPMS — Capteur AV droit absent',
  C2212: 'TPMS — Capteur AR gauche absent',
  C2213: 'TPMS — Capteur AR droit absent',
  C2220: 'TPMS — Pression pneu trop basse',
  C2221: 'TPMS — Pression pneu trop élevée',

  // ── Direction assistée (C-codes) ─────────────────────────────────────────────
  C1500: 'EPS — Capteur couple défaillant',
  C1510: 'EPS — Moteur défaillant',
  C1511: 'EPS — Surchauffe moteur',
  C1520: 'EPS — Module défaillant',

  // ── Airbag / SRS (B-codes) ────────────────────────────────────────────────────
  B0001: 'Airbag conducteur — Circuit défaillant',
  B0002: 'Airbag passager — Circuit défaillant',
  B0010: 'Airbag rideau gauche — Défaut',
  B0011: 'Airbag rideau droit — Défaut',
  B0012: 'Airbag latéral gauche — Défaut',
  B0013: 'Airbag latéral droit — Défaut',
  B0020: 'Prétensionneur ceinture conducteur — Défaut',
  B0021: 'Prétensionneur ceinture passager — Défaut',
  B0028: 'Capteur impact côté gauche — Défaut',
  B0029: 'Capteur impact côté droit — Défaut',
  B0030: 'Capteur impact frontal — Défaut',
  B0051: 'Module airbag — Défaut interne',
  B0095: 'Désactivation airbag passager — Défaut',

  // ── Body / BCM / BSI (B-codes) ────────────────────────────────────────────────
  B1000: 'Module BSI/BCM — Défaut général',
  B1001: 'Module climatisation — Défaut',
  B1318: 'Tension batterie 12V — Trop faible (BSI)',
  B1320: 'Tension batterie 12V — Trop élevée (BSI)',
  B1500: 'Tableau de bord — Défaut interne',
  B1517: 'Combiné instrument — Défaut',
  B2000: 'Lève-vitres — Défaut moteur',
  B2100: 'Verrouillage centralisé — Défaut',
  B2200: 'Climatisation — Capteur évaporateur défaut',
  B2477: 'Compresseur clim — Embrayage défaut',
  B2600: 'Éclairage extérieur — Défaut',

  // ── Network / Réseau CAN (U-codes) ───────────────────────────────────────────
  U0001: 'Bus CAN haute vitesse — Défaut communication',
  U0002: 'Bus CAN haute vitesse — Perte communication',
  U0010: 'Bus CAN moyenne vitesse — Défaut communication',
  U0073: 'Bus CAN A — Off',
  U0100: 'Perte communication calculateur moteur (ECM/PCM)',
  U0101: 'Perte communication boîte de vitesses (TCM)',
  U0103: 'Perte communication module BV (GSM)',
  U0121: 'Perte communication module ABS/ESP',
  U0122: 'Perte communication module stabilité (VDC/ESP)',
  U0125: 'Perte communication module multi-axes',
  U0126: 'Perte communication capteur angle volant',
  U0140: 'Perte communication BSI/BCM',
  U0146: 'Perte communication module passerelle (gateway)',
  U0151: 'Perte communication module airbag',
  U0155: 'Perte communication tableau de bord (cluster)',
  U0164: 'Perte communication module climatisation',
  U0167: 'Perte communication module immobiliseur',
  U0184: 'Perte communication module radio',
  U0190: 'Perte communication module télématique',
  U0235: 'Perte communication régulateur de vitesse',
  U0301: 'Désaccord configuration ECM',
  U0401: 'Données invalides reçues du calculateur moteur',
  U0402: 'Données invalides reçues du TCM',
  U0415: 'Données invalides reçues du module ABS',
  U0418: 'Données invalides reçues du frein de stationnement',
  U0422: 'Données invalides reçues du BSI/BCM',
  U1000: 'Bus CAN classe 2 — Défaut',
  U1100: 'Perte communication moteur (Ford/Chrysler)',
  U1900: 'Bus CAN — Défaut communication général',
}
