export const PLANS = {
  free: {
    id: 'free',
    name: 'Gratuit',
    price: 0,
    priceYearly: 0,
    maxDiagnostics: 2,
    maxDevis: 1,
    maxVehicles: 1,
    historyDays: 7,
    features: [
      '2 diagnostics/mois',
      '1 analyse devis/mois',
      '1 vehicule',
      'Historique 7 jours',
      'Recherche garages',
      'Recherche pieces',
    ],
    notIncluded: [
      'Export PDF',
      'Rappels entretien',
      "Carnet d'entretien",
    ],
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    emoji: '👤',
    subtitle: 'Pour les particuliers',
    price: 9.99,
    priceYearly: 89,
    yearlyDiscount: '2 mois offerts',
    maxDiagnostics: Infinity,
    maxDevis: Infinity,
    maxVehicles: 3,
    historyDays: Infinity,
    features: [
      'Diagnostics illimites',
      'Analyses devis illimitees',
      "Jusqu'a 3 vehicules",
      'Export PDF',
      'Rappels entretien',
      "Carnet d'entretien",
      'Historique permanent',
      'Support email 48h',
    ],
    notIncluded: [
      'Comparateur multi-devis',
      'Rapports mensuels',
      'Multi-utilisateurs',
    ],
    stripePriceMonthly: 'price_premium_monthly',
    stripePriceYearly: 'price_premium_yearly',
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    emoji: '👔',
    subtitle: 'Pour les professionnels',
    badge: 'ENTREPRISE',
    price: 29.99,
    priceYearly: 249,
    yearlyDiscount: '2 mois offerts',
    maxDiagnostics: Infinity,
    maxDevis: Infinity,
    maxVehicles: 15,
    maxTeamMembers: 3,
    historyDays: Infinity,
    features: [
      'Tout Premium inclus',
      "Jusqu'a 15 vehicules",
      'Comparateur multi-devis',
      'Alertes prix pieces',
      'Rapports mensuels',
      'Facturation TVA / SIRET',
      'Multi-utilisateurs (3)',
      'Export CSV/Excel',
      'Badge "Pro verifie"',
      'Support prioritaire 24h',
      'Acces beta nouvelles features',
    ],
    notIncluded: [],
    stripePriceMonthly: 'price_pro_monthly',
    stripePriceYearly: 'price_pro_yearly',
  },
} as const

export type PlanId = keyof typeof PLANS
export type Plan = (typeof PLANS)[PlanId]
