export const PLANS = {
  free: {
    id: 'free',
    name: 'Gratuit',
    price: 0,
    priceYearly: 0,
    maxDiagnostics: 2,
    maxDevis: 1,
    maxVehicles: 1,
    maxChatMessages: 10,
    historyDays: 7,
    features: [
      '2 diagnostics IA/mois',
      '1 véhicule enregistré',
      'Recherche pièces basique',
      'Comparaison prix multi-retailers',
      '10 messages chat mécanicien/mois',
      'Historique limité (3 derniers)',
    ],
    notIncluded: [
      'Analyseur de devis IA',
      'Diagnostic vidéo IA',
      'Prévision de pannes',
      'Chat mécanicien illimité',
      'Véhicules illimités',
      'Support prioritaire',
    ],
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    emoji: '⭐',
    subtitle: 'Tout illimité',
    price: 9.99,
    priceYearly: 89,
    yearlyDiscount: '2 mois offerts',
    maxDiagnostics: Infinity,
    maxDevis: Infinity,
    maxVehicles: Infinity,
    maxChatMessages: Infinity,
    historyDays: Infinity,
    features: [
      'Diagnostics IA illimités',
      'Véhicules illimités',
      'Analyseur de devis IA (anti-arnaque)',
      'Diagnostic vidéo IA',
      'Prévision de pannes intelligente',
      'Chat mécanicien 24/7 illimité',
      'Historique complet + export PDF',
      'Analyse multi-photos',
      'Notifications intelligentes',
      'Support prioritaire',
      'Sans publicité',
    ],
    notIncluded: [],
    stripePriceMonthly: 'price_premium_monthly',
    stripePriceYearly: 'price_premium_yearly',
  },
} as const

export type PlanId = keyof typeof PLANS
export type Plan = (typeof PLANS)[PlanId]
